/*
 * WARNING: This is an autogenerated file. DO NOT EDIT.
 * This file was generated by generate_kernels.sh which intern launches compile_matmul_kernel.py */
#pragma once

#include <string>

const std::string TRITON_MATMUL_KERNEL_10_SOURCE_PTX = R"(
//
// Generated by LLVM NVPTX Back-End
//

.version 8.4
.target sm_89
.address_size 64

	// .globl	matmul_kernel_bias_transpose_a
.extern .shared .align 16 .b8 global_smem[];

.visible .entry matmul_kernel_bias_transpose_a(
	.param .u64 matmul_kernel_bias_transpose_a_param_0,
	.param .u64 matmul_kernel_bias_transpose_a_param_1,
	.param .u64 matmul_kernel_bias_transpose_a_param_2,
	.param .u64 matmul_kernel_bias_transpose_a_param_3,
	.param .u32 matmul_kernel_bias_transpose_a_param_4,
	.param .u32 matmul_kernel_bias_transpose_a_param_5,
	.param .u32 matmul_kernel_bias_transpose_a_param_6,
	.param .u32 matmul_kernel_bias_transpose_a_param_7,
	.param .u32 matmul_kernel_bias_transpose_a_param_8,
	.param .u32 matmul_kernel_bias_transpose_a_param_9
)
.maxntid 256, 1, 1
{
	.reg .pred 	%p<79>;
	.reg .b16 	%rs<789>;
	.reg .b32 	%r<1471>;
	.reg .b64 	%rd<105>;
	.loc	1 41 0
$L__func_begin0:
	.loc	1 41 0

	ld.param.u32 	%r144, [matmul_kernel_bias_transpose_a_param_9];
	ld.param.u32 	%r143, [matmul_kernel_bias_transpose_a_param_6];
	ld.param.u32 	%r142, [matmul_kernel_bias_transpose_a_param_5];
	ld.param.u32 	%r141, [matmul_kernel_bias_transpose_a_param_4];
	ld.param.u64 	%rd23, [matmul_kernel_bias_transpose_a_param_3];
	ld.param.u64 	%rd22, [matmul_kernel_bias_transpose_a_param_2];
	ld.param.u64 	%rd21, [matmul_kernel_bias_transpose_a_param_1];
	ld.param.u64 	%rd36, [matmul_kernel_bias_transpose_a_param_0];
$L__tmp0:
	.loc	1 57 24
	// begin inline asm
	mov.u32 %r145, %ctaid.x;
	// end inline asm
$L__tmp1:
	.loc	2 44 22
	add.s32 	%r210, %r141, 127;
	.loc	2 44 28
	shr.s32 	%r211, %r210, 31;
	shr.u32 	%r212, %r211, 25;
	add.s32 	%r213, %r210, %r212;
	shr.s32 	%r214, %r213, 7;
$L__tmp2:
	.loc	2 44 22
	add.s32 	%r215, %r142, 255;
	.loc	2 44 28
	shr.s32 	%r216, %r215, 31;
	shr.u32 	%r217, %r216, 24;
	add.s32 	%r218, %r215, %r217;
	shr.s32 	%r219, %r218, 8;
$L__tmp3:
	.loc	1 60 38
	shl.b32 	%r221, %r219, 3;
	ld.param.u32 	%r222, [matmul_kernel_bias_transpose_a_param_7];
	ld.param.u32 	%r223, [matmul_kernel_bias_transpose_a_param_8];
	.loc	1 61 22
	div.s32 	%r224, %r145, %r221;
	.loc	1 62 29
	shl.b32 	%r225, %r224, 3;
	.loc	1 63 35
	sub.s32 	%r226, %r214, %r225;
	.loc	1 63 48
	min.s32 	%r227, %r226, 8;
	.loc	1 64 33
	rem.s32 	%r228, %r145, %r227;
	.loc	1 64 27
	add.s32 	%r229, %r225, %r228;
	mul.lo.s32 	%r230, %r224, %r221;
	sub.s32 	%r231, %r145, %r230;
	.loc	1 65 40
	div.s32 	%r232, %r231, %r227;
	.loc	1 74 23
	shl.b32 	%r1, %r229, 7;
	.loc	1 74 51
	mov.u32 	%r2, %tid.x;
	and.b32  	%r3, %r2, 31;
	shl.b32 	%r233, %r2, 3;
	and.b32  	%r234, %r233, 120;
	bfe.u32 	%r4, %r2, 5, 3;
	or.b32  	%r5, %r4, 8;
	or.b32  	%r6, %r4, 16;
	or.b32  	%r7, %r4, 24;
	.loc	1 74 38
	or.b32  	%r235, %r1, %r234;
	.loc	1 74 68
	rem.s32 	%r236, %r235, %r141;
	.loc	1 75 23
	shl.b32 	%r8, %r232, 8;
	.loc	1 75 51
	and.b32  	%r237, %r233, 248;
	.loc	1 75 38
	or.b32  	%r9, %r8, %r237;
	.loc	1 75 68
	rem.s32 	%r238, %r9, %r142;
	.loc	1 77 60
	bfe.u32 	%r239, %r2, 4, 3;
	bfe.u32 	%r10, %r2, 4, 4;
	or.b32  	%r240, %r10, 16;
	.loc	1 77 71
	shl.b32 	%r241, %r222, 4;
	.loc	1 77 53
	mad.lo.s32 	%r242, %r10, %r222, %r236;
	add.s32 	%r243, %r242, %r241;
	.loc	1 77 22
	mul.wide.s32 	%rd37, %r242, 2;
	add.s64 	%rd24, %rd36, %rd37;
	mul.wide.s32 	%rd38, %r243, 2;
	add.s64 	%rd25, %rd36, %rd38;
	.loc	1 78 40
	shl.b32 	%r244, %r223, 3;
	.loc	1 78 52
	mad.lo.s32 	%r245, %r4, %r223, %r238;
	add.s32 	%r246, %r245, %r244;
	add.s32 	%r247, %r246, %r244;
	add.s32 	%r248, %r247, %r244;
	.loc	1 78 22
	mul.wide.s32 	%rd39, %r245, 2;
	add.s64 	%rd26, %rd21, %rd39;
	mul.wide.s32 	%rd40, %r246, 2;
	add.s64 	%rd27, %rd21, %rd40;
	mul.wide.s32 	%rd41, %r247, 2;
	add.s64 	%rd28, %rd21, %rd41;
	mul.wide.s32 	%rd42, %r248, 2;
	add.s64 	%rd29, %rd21, %rd42;
$L__tmp4:
	.loc	2 44 22
	add.s32 	%r249, %r143, 31;
$L__tmp5:
	.loc	1 102 33
	shl.b32 	%r253, %r222, 5;
	.loc	1 103 33
	shl.b32 	%r254, %r223, 5;
	.loc	1 93 22
	setp.lt.s32 	%p13, %r249, 32;
	setp.gt.s32 	%p14, %r249, 31;
	.loc	1 96 72
	setp.lt.s32 	%p15, %r10, %r143;
	setp.lt.s32 	%p16, %r240, %r143;
	.loc	1 96 20
	shl.b32 	%r255, %r10, 7;
	and.b32  	%r256, %r2, 15;
	xor.b32  	%r257, %r239, %r256;
	shl.b32 	%r258, %r257, 3;
	or.b32  	%r12, %r255, %r258;
	shl.b32 	%r259, %r12, 1;
	mov.u32 	%r260, global_smem;
	add.s32 	%r146, %r260, %r259;
	shl.b32 	%r261, %r240, 7;
	or.b32  	%r13, %r261, %r258;
	shl.b32 	%r262, %r13, 1;
	add.s32 	%r148, %r260, %r262;
	selp.b32 	%r263, 16, 0, %p14;
	selp.b32 	%r147, %r263, 0, %p15;
	mov.pred 	%p1, -1;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r146 + 0 ], [ %rd24 + 0 ], 0x10, %r147;
	// end inline asm
	selp.b32 	%r149, %r263, 0, %p16;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r148 + 0 ], [ %rd25 + 0 ], 0x10, %r149;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 72
	setp.lt.s32 	%p17, %r4, %r143;
	setp.lt.s32 	%p18, %r5, %r143;
	setp.lt.s32 	%p19, %r6, %r143;
	setp.lt.s32 	%p20, %r7, %r143;
	.loc	1 97 20
	shl.b32 	%r264, %r4, 8;
	xor.b32  	%r265, %r4, %r3;
	shl.b32 	%r266, %r265, 3;
	or.b32  	%r14, %r266, %r264;
	shl.b32 	%r267, %r14, 1;
	add.s32 	%r268, %r260, 16384;
	add.s32 	%r150, %r268, %r267;
	shl.b32 	%r269, %r5, 8;
	or.b32  	%r15, %r269, %r266;
	shl.b32 	%r270, %r15, 1;
	add.s32 	%r152, %r268, %r270;
	shl.b32 	%r271, %r6, 8;
	or.b32  	%r16, %r271, %r266;
	shl.b32 	%r272, %r16, 1;
	add.s32 	%r154, %r268, %r272;
	shl.b32 	%r273, %r7, 8;
	or.b32  	%r17, %r273, %r266;
	shl.b32 	%r274, %r17, 1;
	add.s32 	%r156, %r268, %r274;
	selp.b32 	%r151, %r263, 0, %p17;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r150 + 0 ], [ %rd26 + 0 ], 0x10, %r151;
	// end inline asm
	selp.b32 	%r153, %r263, 0, %p18;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r152 + 0 ], [ %rd27 + 0 ], 0x10, %r153;
	// end inline asm
	selp.b32 	%r155, %r263, 0, %p19;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r154 + 0 ], [ %rd28 + 0 ], 0x10, %r155;
	// end inline asm
	selp.b32 	%r157, %r263, 0, %p20;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r156 + 0 ], [ %rd29 + 0 ], 0x10, %r157;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	setp.gt.s32 	%p21, %r249, 63;
	.loc	1 102 18
	mul.wide.s32 	%rd43, %r253, 2;
	add.s64 	%rd30, %rd24, %rd43;
	add.s64 	%rd31, %rd25, %rd43;
	.loc	1 103 18
	mul.wide.s32 	%rd44, %r254, 2;
	add.s64 	%rd32, %rd26, %rd44;
	add.s64 	%rd33, %rd27, %rd44;
	add.s64 	%rd34, %rd28, %rd44;
	add.s64 	%rd35, %rd29, %rd44;
	.loc	1 96 53
	or.b32  	%r275, %r10, 32;
	or.b32  	%r276, %r10, 48;
	.loc	1 96 72
	setp.lt.s32 	%p22, %r275, %r143;
	setp.lt.s32 	%p23, %r276, %r143;
	.loc	1 96 20
	bar.sync 	0;
	add.s32 	%r277, %r260, 8192;
	add.s32 	%r158, %r277, %r259;
	add.s32 	%r160, %r277, %r262;
	selp.b32 	%r278, 16, 0, %p21;
	selp.b32 	%r159, %r278, 0, %p22;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r158 + 0 ], [ %rd30 + 0 ], 0x10, %r159;
	// end inline asm
	selp.b32 	%r161, %r278, 0, %p23;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r160 + 0 ], [ %rd31 + 0 ], 0x10, %r161;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 53
	or.b32  	%r18, %r4, 32;
	or.b32  	%r19, %r4, 40;
	or.b32  	%r20, %r4, 48;
	or.b32  	%r21, %r4, 56;
	.loc	1 97 72
	setp.lt.s32 	%p24, %r18, %r143;
	setp.lt.s32 	%p25, %r19, %r143;
	setp.lt.s32 	%p26, %r20, %r143;
	setp.lt.s32 	%p27, %r21, %r143;
	.loc	1 97 20
	add.s32 	%r279, %r260, 32768;
	add.s32 	%r162, %r279, %r267;
	add.s32 	%r164, %r279, %r270;
	add.s32 	%r166, %r279, %r272;
	add.s32 	%r168, %r279, %r274;
	selp.b32 	%r163, %r278, 0, %p24;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r162 + 0 ], [ %rd32 + 0 ], 0x10, %r163;
	// end inline asm
	selp.b32 	%r165, %r278, 0, %p25;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r164 + 0 ], [ %rd33 + 0 ], 0x10, %r165;
	// end inline asm
	selp.b32 	%r167, %r278, 0, %p26;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r166 + 0 ], [ %rd34 + 0 ], 0x10, %r167;
	// end inline asm
	selp.b32 	%r169, %r278, 0, %p27;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r168 + 0 ], [ %rd35 + 0 ], 0x10, %r169;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 96 20
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	bfe.u32 	%r22, %r2, 7, 1;
	and.b32  	%r280, %r2, 7;
	bfe.u32 	%r281, %r2, 3, 1;
	bfe.u32 	%r282, %r2, 4, 1;
	shl.b32 	%r283, %r22, 1;
	or.b32  	%r284, %r283, %r281;
	xor.b32  	%r285, %r284, %r280;
	shl.b32 	%r286, %r280, 7;
	shl.b32 	%r287, %r282, 10;
	or.b32  	%r288, %r287, %r286;
	shl.b32 	%r289, %r285, 3;
	or.b32  	%r23, %r289, %r288;
	shl.b32 	%r290, %r23, 1;
	add.s32 	%r174, %r260, %r290;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1462, %r1463, %r1464, %r1465 }, [ %r174 + 0 ];
	// end inline asm
	or.b32  	%r291, %r284, 4;
	xor.b32  	%r292, %r291, %r280;
	shl.b32 	%r293, %r292, 3;
	or.b32  	%r28, %r293, %r288;
	shl.b32 	%r294, %r28, 1;
	add.s32 	%r179, %r260, %r294;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1458, %r1459, %r1460, %r1461 }, [ %r179 + 0 ];
	// end inline asm
	or.b32  	%r295, %r284, 8;
	xor.b32  	%r296, %r295, %r280;
	shl.b32 	%r297, %r296, 3;
	or.b32  	%r33, %r297, %r288;
	shl.b32 	%r298, %r33, 1;
	add.s32 	%r184, %r260, %r298;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1454, %r1455, %r1456, %r1457 }, [ %r184 + 0 ];
	// end inline asm
	or.b32  	%r299, %r284, 12;
	xor.b32  	%r300, %r299, %r280;
	shl.b32 	%r301, %r300, 3;
	or.b32  	%r38, %r301, %r288;
	shl.b32 	%r302, %r38, 1;
	add.s32 	%r189, %r260, %r302;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1450, %r1451, %r1452, %r1453 }, [ %r189 + 0 ];
	// end inline asm
	.loc	1 97 20
	bfe.u32 	%r43, %r2, 5, 2;
	shl.b32 	%r303, %r282, 2;
	or.b32  	%r304, %r303, %r43;
	xor.b32  	%r305, %r304, %r280;
	shl.b32 	%r306, %r256, 8;
	shl.b32 	%r307, %r305, 3;
	or.b32  	%r44, %r307, %r306;
	shl.b32 	%r308, %r44, 1;
	add.s32 	%r194, %r268, %r308;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1446, %r1447, %r1448, %r1449 }, [ %r194 + 0 ];
	// end inline asm
	or.b32  	%r309, %r304, 8;
	xor.b32  	%r310, %r309, %r280;
	shl.b32 	%r311, %r310, 3;
	add.s32 	%r49, %r311, %r306;
	shl.b32 	%r312, %r49, 1;
	add.s32 	%r199, %r268, %r312;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1442, %r1443, %r1444, %r1445 }, [ %r199 + 0 ];
	// end inline asm
	or.b32  	%r313, %r304, 16;
	xor.b32  	%r314, %r313, %r280;
	shl.b32 	%r315, %r314, 3;
	add.s32 	%r54, %r315, %r306;
	shl.b32 	%r316, %r54, 1;
	add.s32 	%r204, %r268, %r316;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1438, %r1439, %r1440, %r1441 }, [ %r204 + 0 ];
	// end inline asm
	or.b32  	%r317, %r304, 24;
	xor.b32  	%r318, %r317, %r280;
	shl.b32 	%r319, %r318, 3;
	add.s32 	%r59, %r319, %r306;
	shl.b32 	%r320, %r59, 1;
	add.s32 	%r209, %r268, %r320;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1434, %r1435, %r1436, %r1437 }, [ %r209 + 0 ];
	// end inline asm
	mov.b16 	%rs661, 0x0000;
	mov.u16 	%rs662, %rs661;
	mov.u16 	%rs663, %rs661;
	mov.u16 	%rs664, %rs661;
	mov.u16 	%rs665, %rs661;
	mov.u16 	%rs666, %rs661;
	mov.u16 	%rs667, %rs661;
	mov.u16 	%rs668, %rs661;
	mov.u16 	%rs669, %rs661;
	mov.u16 	%rs670, %rs661;
	mov.u16 	%rs671, %rs661;
	mov.u16 	%rs672, %rs661;
	mov.u16 	%rs673, %rs661;
	mov.u16 	%rs674, %rs661;
	mov.u16 	%rs675, %rs661;
	mov.u16 	%rs676, %rs661;
	mov.u16 	%rs677, %rs661;
	mov.u16 	%rs678, %rs661;
	mov.u16 	%rs679, %rs661;
	mov.u16 	%rs680, %rs661;
	mov.u16 	%rs681, %rs661;
	mov.u16 	%rs682, %rs661;
	mov.u16 	%rs683, %rs661;
	mov.u16 	%rs684, %rs661;
	mov.u16 	%rs685, %rs661;
	mov.u16 	%rs686, %rs661;
	mov.u16 	%rs687, %rs661;
	mov.u16 	%rs688, %rs661;
	mov.u16 	%rs689, %rs661;
	mov.u16 	%rs690, %rs661;
	mov.u16 	%rs691, %rs661;
	mov.u16 	%rs692, %rs661;
	mov.u16 	%rs693, %rs661;
	mov.u16 	%rs694, %rs661;
	mov.u16 	%rs695, %rs661;
	mov.u16 	%rs696, %rs661;
	mov.u16 	%rs697, %rs661;
	mov.u16 	%rs698, %rs661;
	mov.u16 	%rs699, %rs661;
	mov.u16 	%rs700, %rs661;
	mov.u16 	%rs701, %rs661;
	mov.u16 	%rs702, %rs661;
	mov.u16 	%rs703, %rs661;
	mov.u16 	%rs704, %rs661;
	mov.u16 	%rs705, %rs661;
	mov.u16 	%rs706, %rs661;
	mov.u16 	%rs707, %rs661;
	mov.u16 	%rs708, %rs661;
	mov.u16 	%rs709, %rs661;
	mov.u16 	%rs710, %rs661;
	mov.u16 	%rs711, %rs661;
	mov.u16 	%rs712, %rs661;
	mov.u16 	%rs713, %rs661;
	mov.u16 	%rs714, %rs661;
	mov.u16 	%rs715, %rs661;
	mov.u16 	%rs716, %rs661;
	mov.u16 	%rs717, %rs661;
	mov.u16 	%rs718, %rs661;
	mov.u16 	%rs719, %rs661;
	mov.u16 	%rs720, %rs661;
	mov.u16 	%rs721, %rs661;
	mov.u16 	%rs722, %rs661;
	mov.u16 	%rs723, %rs661;
	mov.u16 	%rs724, %rs661;
	mov.u16 	%rs725, %rs661;
	mov.u16 	%rs726, %rs661;
	mov.u16 	%rs727, %rs661;
	mov.u16 	%rs728, %rs661;
	mov.u16 	%rs729, %rs661;
	mov.u16 	%rs730, %rs661;
	mov.u16 	%rs731, %rs661;
	mov.u16 	%rs732, %rs661;
	mov.u16 	%rs733, %rs661;
	mov.u16 	%rs734, %rs661;
	mov.u16 	%rs735, %rs661;
	mov.u16 	%rs736, %rs661;
	mov.u16 	%rs737, %rs661;
	mov.u16 	%rs738, %rs661;
	mov.u16 	%rs739, %rs661;
	mov.u16 	%rs740, %rs661;
	mov.u16 	%rs741, %rs661;
	mov.u16 	%rs742, %rs661;
	mov.u16 	%rs743, %rs661;
	mov.u16 	%rs744, %rs661;
	mov.u16 	%rs745, %rs661;
	mov.u16 	%rs746, %rs661;
	mov.u16 	%rs747, %rs661;
	mov.u16 	%rs748, %rs661;
	mov.u16 	%rs749, %rs661;
	mov.u16 	%rs750, %rs661;
	mov.u16 	%rs751, %rs661;
	mov.u16 	%rs752, %rs661;
	mov.u16 	%rs753, %rs661;
	mov.u16 	%rs754, %rs661;
	mov.u16 	%rs755, %rs661;
	mov.u16 	%rs756, %rs661;
	mov.u16 	%rs757, %rs661;
	mov.u16 	%rs758, %rs661;
	mov.u16 	%rs759, %rs661;
	mov.u16 	%rs760, %rs661;
	mov.u16 	%rs761, %rs661;
	mov.u16 	%rs762, %rs661;
	mov.u16 	%rs763, %rs661;
	mov.u16 	%rs764, %rs661;
	mov.u16 	%rs765, %rs661;
	mov.u16 	%rs766, %rs661;
	mov.u16 	%rs767, %rs661;
	mov.u16 	%rs768, %rs661;
	mov.u16 	%rs769, %rs661;
	mov.u16 	%rs770, %rs661;
	mov.u16 	%rs771, %rs661;
	mov.u16 	%rs772, %rs661;
	mov.u16 	%rs773, %rs661;
	mov.u16 	%rs774, %rs661;
	mov.u16 	%rs775, %rs661;
	mov.u16 	%rs776, %rs661;
	mov.u16 	%rs777, %rs661;
	mov.u16 	%rs778, %rs661;
	mov.u16 	%rs779, %rs661;
	mov.u16 	%rs780, %rs661;
	mov.u16 	%rs781, %rs661;
	mov.u16 	%rs782, %rs661;
	mov.u16 	%rs783, %rs661;
	mov.u16 	%rs784, %rs661;
	mov.u16 	%rs785, %rs661;
	mov.u16 	%rs786, %rs661;
	mov.u16 	%rs787, %rs661;
	mov.u16 	%rs788, %rs661;
	.loc	1 93 22
	@%p13 bra 	$L__BB0_3;
	.loc	1 0 22
	cvt.s64.s32 	%rd3, %r245;
	cvt.s64.s32 	%rd4, %r246;
	cvt.s64.s32 	%rd5, %r247;
	cvt.s64.s32 	%rd6, %r248;
	shr.s32 	%r250, %r249, 31;
	shr.u32 	%r251, %r250, 27;
	add.s32 	%r252, %r249, %r251;
	shr.s32 	%r11, %r252, 5;
	cvt.s64.s32 	%rd7, %r253;
	cvt.s64.s32 	%rd8, %r254;
	add.s32 	%r64, %r11, -2;
	.loc	1 93 22
	shl.b64 	%rd9, %rd6, 1;
	shl.b64 	%rd45, %rd8, 2;
	add.s64 	%rd104, %rd21, %rd45;
	shl.b64 	%rd11, %rd8, 1;
	shl.b64 	%rd12, %rd5, 1;
	shl.b64 	%rd13, %rd4, 1;
	shl.b64 	%rd14, %rd3, 1;
	shl.b64 	%rd103, %rd7, 2;
	shl.b64 	%rd16, %rd7, 1;
	mov.b16 	%rs661, 0x0000;
	mov.b32 	%r1469, 1;
	mov.b32 	%r1433, 0;
	mov.u32 	%r1466, %r268;
	mov.u32 	%r1467, %r260;
	mov.u32 	%r1468, %r1433;
	mov.u16 	%rs662, %rs661;
	mov.u16 	%rs663, %rs661;
	mov.u16 	%rs664, %rs661;
	mov.u16 	%rs665, %rs661;
	mov.u16 	%rs666, %rs661;
	mov.u16 	%rs667, %rs661;
	mov.u16 	%rs668, %rs661;
	mov.u16 	%rs669, %rs661;
	mov.u16 	%rs670, %rs661;
	mov.u16 	%rs671, %rs661;
	mov.u16 	%rs672, %rs661;
	mov.u16 	%rs673, %rs661;
	mov.u16 	%rs674, %rs661;
	mov.u16 	%rs675, %rs661;
	mov.u16 	%rs676, %rs661;
	mov.u16 	%rs677, %rs661;
	mov.u16 	%rs678, %rs661;
	mov.u16 	%rs679, %rs661;
	mov.u16 	%rs680, %rs661;
	mov.u16 	%rs681, %rs661;
	mov.u16 	%rs682, %rs661;
	mov.u16 	%rs683, %rs661;
	mov.u16 	%rs684, %rs661;
	mov.u16 	%rs685, %rs661;
	mov.u16 	%rs686, %rs661;
	mov.u16 	%rs687, %rs661;
	mov.u16 	%rs688, %rs661;
	mov.u16 	%rs689, %rs661;
	mov.u16 	%rs690, %rs661;
	mov.u16 	%rs691, %rs661;
	mov.u16 	%rs692, %rs661;
	mov.u16 	%rs693, %rs661;
	mov.u16 	%rs694, %rs661;
	mov.u16 	%rs695, %rs661;
	mov.u16 	%rs696, %rs661;
	mov.u16 	%rs697, %rs661;
	mov.u16 	%rs698, %rs661;
	mov.u16 	%rs699, %rs661;
	mov.u16 	%rs700, %rs661;
	mov.u16 	%rs701, %rs661;
	mov.u16 	%rs702, %rs661;
	mov.u16 	%rs703, %rs661;
	mov.u16 	%rs704, %rs661;
	mov.u16 	%rs705, %rs661;
	mov.u16 	%rs706, %rs661;
	mov.u16 	%rs707, %rs661;
	mov.u16 	%rs708, %rs661;
	mov.u16 	%rs709, %rs661;
	mov.u16 	%rs710, %rs661;
	mov.u16 	%rs711, %rs661;
	mov.u16 	%rs712, %rs661;
	mov.u16 	%rs713, %rs661;
	mov.u16 	%rs714, %rs661;
	mov.u16 	%rs715, %rs661;
	mov.u16 	%rs716, %rs661;
	mov.u16 	%rs717, %rs661;
	mov.u16 	%rs718, %rs661;
	mov.u16 	%rs719, %rs661;
	mov.u16 	%rs720, %rs661;
	mov.u16 	%rs721, %rs661;
	mov.u16 	%rs722, %rs661;
	mov.u16 	%rs723, %rs661;
	mov.u16 	%rs724, %rs661;
	mov.u16 	%rs725, %rs661;
	mov.u16 	%rs726, %rs661;
	mov.u16 	%rs727, %rs661;
	mov.u16 	%rs728, %rs661;
	mov.u16 	%rs729, %rs661;
	mov.u16 	%rs730, %rs661;
	mov.u16 	%rs731, %rs661;
	mov.u16 	%rs732, %rs661;
	mov.u16 	%rs733, %rs661;
	mov.u16 	%rs734, %rs661;
	mov.u16 	%rs735, %rs661;
	mov.u16 	%rs736, %rs661;
	mov.u16 	%rs737, %rs661;
	mov.u16 	%rs738, %rs661;
	mov.u16 	%rs739, %rs661;
	mov.u16 	%rs740, %rs661;
	mov.u16 	%rs741, %rs661;
	mov.u16 	%rs742, %rs661;
	mov.u16 	%rs743, %rs661;
	mov.u16 	%rs744, %rs661;
	mov.u16 	%rs745, %rs661;
	mov.u16 	%rs746, %rs661;
	mov.u16 	%rs747, %rs661;
	mov.u16 	%rs748, %rs661;
	mov.u16 	%rs749, %rs661;
	mov.u16 	%rs750, %rs661;
	mov.u16 	%rs751, %rs661;
	mov.u16 	%rs752, %rs661;
	mov.u16 	%rs753, %rs661;
	mov.u16 	%rs754, %rs661;
	mov.u16 	%rs755, %rs661;
	mov.u16 	%rs756, %rs661;
	mov.u16 	%rs757, %rs661;
	mov.u16 	%rs758, %rs661;
	mov.u16 	%rs759, %rs661;
	mov.u16 	%rs760, %rs661;
	mov.u16 	%rs761, %rs661;
	mov.u16 	%rs762, %rs661;
	mov.u16 	%rs763, %rs661;
	mov.u16 	%rs764, %rs661;
	mov.u16 	%rs765, %rs661;
	mov.u16 	%rs766, %rs661;
	mov.u16 	%rs767, %rs661;
	mov.u16 	%rs768, %rs661;
	mov.u16 	%rs769, %rs661;
	mov.u16 	%rs770, %rs661;
	mov.u16 	%rs771, %rs661;
	mov.u16 	%rs772, %rs661;
	mov.u16 	%rs773, %rs661;
	mov.u16 	%rs774, %rs661;
	mov.u16 	%rs775, %rs661;
	mov.u16 	%rs776, %rs661;
	mov.u16 	%rs777, %rs661;
	mov.u16 	%rs778, %rs661;
	mov.u16 	%rs779, %rs661;
	mov.u16 	%rs780, %rs661;
	mov.u16 	%rs781, %rs661;
	mov.u16 	%rs782, %rs661;
	mov.u16 	%rs783, %rs661;
	mov.u16 	%rs784, %rs661;
	mov.u16 	%rs785, %rs661;
	mov.u16 	%rs786, %rs661;
	mov.u16 	%rs787, %rs661;
	mov.u16 	%rs788, %rs661;
	mov.u32 	%r1470, %r1433;
$L__BB0_2:
	setp.lt.s32 	%p34, %r1470, %r64;
	.loc	1 96 20
	add.s32 	%r1058, %r1467, %r290;
	add.s32 	%r329, %r1058, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r689, %r690, %r691, %r692 }, [ %r329 + 0 ];
	// end inline asm
	add.s32 	%r1060, %r1467, %r294;
	add.s32 	%r334, %r1060, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r769, %r770, %r771, %r772 }, [ %r334 + 0 ];
	// end inline asm
	add.s32 	%r1062, %r1467, %r298;
	add.s32 	%r339, %r1062, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r849, %r850, %r851, %r852 }, [ %r339 + 0 ];
	// end inline asm
	add.s32 	%r1064, %r1467, %r302;
	add.s32 	%r344, %r1064, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r929, %r930, %r931, %r932 }, [ %r344 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r1066, %r1466, %r308;
	add.s32 	%r349, %r1066, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r693, %r694, %r703, %r704 }, [ %r349 + 0 ];
	// end inline asm
	add.s32 	%r1068, %r1466, %r312;
	add.s32 	%r354, %r1068, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r713, %r714, %r723, %r724 }, [ %r354 + 0 ];
	// end inline asm
	add.s32 	%r1070, %r1466, %r316;
	add.s32 	%r359, %r1070, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r733, %r734, %r743, %r744 }, [ %r359 + 0 ];
	// end inline asm
	add.s32 	%r1072, %r1466, %r320;
	add.s32 	%r364, %r1072, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r753, %r754, %r763, %r764 }, [ %r364 + 0 ];
	// end inline asm
	.loc	1 100 35
	mov.b32 	%r685, {%rs661, %rs662};
	mov.b32 	%r686, {%rs663, %rs664};
	mov.b32 	%r695, {%rs665, %rs666};
	mov.b32 	%r696, {%rs667, %rs668};
	mov.b32 	%r705, {%rs669, %rs670};
	mov.b32 	%r706, {%rs671, %rs672};
	mov.b32 	%r715, {%rs673, %rs674};
	mov.b32 	%r716, {%rs675, %rs676};
	mov.b32 	%r725, {%rs677, %rs678};
	mov.b32 	%r726, {%rs679, %rs680};
	mov.b32 	%r735, {%rs681, %rs682};
	mov.b32 	%r736, {%rs683, %rs684};
	mov.b32 	%r745, {%rs685, %rs686};
	mov.b32 	%r746, {%rs687, %rs688};
	mov.b32 	%r755, {%rs689, %rs690};
	mov.b32 	%r756, {%rs691, %rs692};
	mov.b32 	%r765, {%rs693, %rs694};
	mov.b32 	%r766, {%rs695, %rs696};
	mov.b32 	%r775, {%rs697, %rs698};
	mov.b32 	%r776, {%rs699, %rs700};
	mov.b32 	%r785, {%rs701, %rs702};
	mov.b32 	%r786, {%rs703, %rs704};
	mov.b32 	%r795, {%rs705, %rs706};
	mov.b32 	%r796, {%rs707, %rs708};
	mov.b32 	%r805, {%rs709, %rs710};
	mov.b32 	%r806, {%rs711, %rs712};
	mov.b32 	%r815, {%rs713, %rs714};
	mov.b32 	%r816, {%rs715, %rs716};
	mov.b32 	%r825, {%rs717, %rs718};
	mov.b32 	%r826, {%rs719, %rs720};
	mov.b32 	%r835, {%rs721, %rs722};
	mov.b32 	%r836, {%rs723, %rs724};
	mov.b32 	%r845, {%rs725, %rs726};
	mov.b32 	%r846, {%rs727, %rs728};
	mov.b32 	%r855, {%rs729, %rs730};
	mov.b32 	%r856, {%rs731, %rs732};
	mov.b32 	%r865, {%rs733, %rs734};
	mov.b32 	%r866, {%rs735, %rs736};
	mov.b32 	%r875, {%rs737, %rs738};
	mov.b32 	%r876, {%rs739, %rs740};
	mov.b32 	%r885, {%rs741, %rs742};
	mov.b32 	%r886, {%rs743, %rs744};
	mov.b32 	%r895, {%rs745, %rs746};
	mov.b32 	%r896, {%rs747, %rs748};
	mov.b32 	%r905, {%rs749, %rs750};
	mov.b32 	%r906, {%rs751, %rs752};
	mov.b32 	%r915, {%rs753, %rs754};
	mov.b32 	%r916, {%rs755, %rs756};
	mov.b32 	%r925, {%rs757, %rs758};
	mov.b32 	%r926, {%rs759, %rs760};
	mov.b32 	%r935, {%rs761, %rs762};
	mov.b32 	%r936, {%rs763, %rs764};
	mov.b32 	%r945, {%rs765, %rs766};
	mov.b32 	%r946, {%rs767, %rs768};
	mov.b32 	%r955, {%rs769, %rs770};
	mov.b32 	%r956, {%rs771, %rs772};
	mov.b32 	%r965, {%rs773, %rs774};
	mov.b32 	%r966, {%rs775, %rs776};
	mov.b32 	%r975, {%rs777, %rs778};
	mov.b32 	%r976, {%rs779, %rs780};
	mov.b32 	%r985, {%rs781, %rs782};
	mov.b32 	%r986, {%rs783, %rs784};
	mov.b32 	%r995, {%rs785, %rs786};
	mov.b32 	%r996, {%rs787, %rs788};
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r685, %r686 }, { %r1462, %r1463, %r1464, %r1465 }, { %r1446, %r1447 }, { %r685, %r686 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r695, %r696 }, { %r1462, %r1463, %r1464, %r1465 }, { %r1448, %r1449 }, { %r695, %r696 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r705, %r706 }, { %r1462, %r1463, %r1464, %r1465 }, { %r1442, %r1443 }, { %r705, %r706 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r715, %r716 }, { %r1462, %r1463, %r1464, %r1465 }, { %r1444, %r1445 }, { %r715, %r716 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r725, %r726 }, { %r1462, %r1463, %r1464, %r1465 }, { %r1438, %r1439 }, { %r725, %r726 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r735, %r736 }, { %r1462, %r1463, %r1464, %r1465 }, { %r1440, %r1441 }, { %r735, %r736 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r745, %r746 }, { %r1462, %r1463, %r1464, %r1465 }, { %r1434, %r1435 }, { %r745, %r746 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r755, %r756 }, { %r1462, %r1463, %r1464, %r1465 }, { %r1436, %r1437 }, { %r755, %r756 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r765, %r766 }, { %r1458, %r1459, %r1460, %r1461 }, { %r1446, %r1447 }, { %r765, %r766 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r775, %r776 }, { %r1458, %r1459, %r1460, %r1461 }, { %r1448, %r1449 }, { %r775, %r776 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r785, %r786 }, { %r1458, %r1459, %r1460, %r1461 }, { %r1442, %r1443 }, { %r785, %r786 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r795, %r796 }, { %r1458, %r1459, %r1460, %r1461 }, { %r1444, %r1445 }, { %r795, %r796 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r805, %r806 }, { %r1458, %r1459, %r1460, %r1461 }, { %r1438, %r1439 }, { %r805, %r806 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r815, %r816 }, { %r1458, %r1459, %r1460, %r1461 }, { %r1440, %r1441 }, { %r815, %r816 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r825, %r826 }, { %r1458, %r1459, %r1460, %r1461 }, { %r1434, %r1435 }, { %r825, %r826 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r835, %r836 }, { %r1458, %r1459, %r1460, %r1461 }, { %r1436, %r1437 }, { %r835, %r836 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r845, %r846 }, { %r1454, %r1455, %r1456, %r1457 }, { %r1446, %r1447 }, { %r845, %r846 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r855, %r856 }, { %r1454, %r1455, %r1456, %r1457 }, { %r1448, %r1449 }, { %r855, %r856 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r865, %r866 }, { %r1454, %r1455, %r1456, %r1457 }, { %r1442, %r1443 }, { %r865, %r866 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r875, %r876 }, { %r1454, %r1455, %r1456, %r1457 }, { %r1444, %r1445 }, { %r875, %r876 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r885, %r886 }, { %r1454, %r1455, %r1456, %r1457 }, { %r1438, %r1439 }, { %r885, %r886 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r895, %r896 }, { %r1454, %r1455, %r1456, %r1457 }, { %r1440, %r1441 }, { %r895, %r896 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r905, %r906 }, { %r1454, %r1455, %r1456, %r1457 }, { %r1434, %r1435 }, { %r905, %r906 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r915, %r916 }, { %r1454, %r1455, %r1456, %r1457 }, { %r1436, %r1437 }, { %r915, %r916 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r925, %r926 }, { %r1450, %r1451, %r1452, %r1453 }, { %r1446, %r1447 }, { %r925, %r926 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r935, %r936 }, { %r1450, %r1451, %r1452, %r1453 }, { %r1448, %r1449 }, { %r935, %r936 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r945, %r946 }, { %r1450, %r1451, %r1452, %r1453 }, { %r1442, %r1443 }, { %r945, %r946 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r955, %r956 }, { %r1450, %r1451, %r1452, %r1453 }, { %r1444, %r1445 }, { %r955, %r956 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r965, %r966 }, { %r1450, %r1451, %r1452, %r1453 }, { %r1438, %r1439 }, { %r965, %r966 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r975, %r976 }, { %r1450, %r1451, %r1452, %r1453 }, { %r1440, %r1441 }, { %r975, %r976 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r985, %r986 }, { %r1450, %r1451, %r1452, %r1453 }, { %r1434, %r1435 }, { %r985, %r986 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r995, %r996 }, { %r1450, %r1451, %r1452, %r1453 }, { %r1436, %r1437 }, { %r995, %r996 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r685, %r686 }, { %r689, %r690, %r691, %r692 }, { %r693, %r694 }, { %r685, %r686 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r695, %r696 }, { %r689, %r690, %r691, %r692 }, { %r703, %r704 }, { %r695, %r696 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r705, %r706 }, { %r689, %r690, %r691, %r692 }, { %r713, %r714 }, { %r705, %r706 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r715, %r716 }, { %r689, %r690, %r691, %r692 }, { %r723, %r724 }, { %r715, %r716 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r725, %r726 }, { %r689, %r690, %r691, %r692 }, { %r733, %r734 }, { %r725, %r726 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r735, %r736 }, { %r689, %r690, %r691, %r692 }, { %r743, %r744 }, { %r735, %r736 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r745, %r746 }, { %r689, %r690, %r691, %r692 }, { %r753, %r754 }, { %r745, %r746 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r755, %r756 }, { %r689, %r690, %r691, %r692 }, { %r763, %r764 }, { %r755, %r756 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r765, %r766 }, { %r769, %r770, %r771, %r772 }, { %r693, %r694 }, { %r765, %r766 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r775, %r776 }, { %r769, %r770, %r771, %r772 }, { %r703, %r704 }, { %r775, %r776 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r785, %r786 }, { %r769, %r770, %r771, %r772 }, { %r713, %r714 }, { %r785, %r786 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r795, %r796 }, { %r769, %r770, %r771, %r772 }, { %r723, %r724 }, { %r795, %r796 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r805, %r806 }, { %r769, %r770, %r771, %r772 }, { %r733, %r734 }, { %r805, %r806 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r815, %r816 }, { %r769, %r770, %r771, %r772 }, { %r743, %r744 }, { %r815, %r816 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r825, %r826 }, { %r769, %r770, %r771, %r772 }, { %r753, %r754 }, { %r825, %r826 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r835, %r836 }, { %r769, %r770, %r771, %r772 }, { %r763, %r764 }, { %r835, %r836 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r845, %r846 }, { %r849, %r850, %r851, %r852 }, { %r693, %r694 }, { %r845, %r846 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r855, %r856 }, { %r849, %r850, %r851, %r852 }, { %r703, %r704 }, { %r855, %r856 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r865, %r866 }, { %r849, %r850, %r851, %r852 }, { %r713, %r714 }, { %r865, %r866 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r875, %r876 }, { %r849, %r850, %r851, %r852 }, { %r723, %r724 }, { %r875, %r876 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r885, %r886 }, { %r849, %r850, %r851, %r852 }, { %r733, %r734 }, { %r885, %r886 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r895, %r896 }, { %r849, %r850, %r851, %r852 }, { %r743, %r744 }, { %r895, %r896 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r905, %r906 }, { %r849, %r850, %r851, %r852 }, { %r753, %r754 }, { %r905, %r906 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r915, %r916 }, { %r849, %r850, %r851, %r852 }, { %r763, %r764 }, { %r915, %r916 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r925, %r926 }, { %r929, %r930, %r931, %r932 }, { %r693, %r694 }, { %r925, %r926 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r935, %r936 }, { %r929, %r930, %r931, %r932 }, { %r703, %r704 }, { %r935, %r936 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r945, %r946 }, { %r929, %r930, %r931, %r932 }, { %r713, %r714 }, { %r945, %r946 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r955, %r956 }, { %r929, %r930, %r931, %r932 }, { %r723, %r724 }, { %r955, %r956 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r965, %r966 }, { %r929, %r930, %r931, %r932 }, { %r733, %r734 }, { %r965, %r966 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r975, %r976 }, { %r929, %r930, %r931, %r932 }, { %r743, %r744 }, { %r975, %r976 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r985, %r986 }, { %r929, %r930, %r931, %r932 }, { %r753, %r754 }, { %r985, %r986 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r995, %r996 }, { %r929, %r930, %r931, %r932 }, { %r763, %r764 }, { %r995, %r996 };
	// end inline asm
	mov.b32 	{%rs661, %rs662}, %r685;
	mov.b32 	{%rs663, %rs664}, %r686;
	mov.b32 	{%rs665, %rs666}, %r695;
	mov.b32 	{%rs667, %rs668}, %r696;
	mov.b32 	{%rs669, %rs670}, %r705;
	mov.b32 	{%rs671, %rs672}, %r706;
	mov.b32 	{%rs673, %rs674}, %r715;
	mov.b32 	{%rs675, %rs676}, %r716;
	mov.b32 	{%rs677, %rs678}, %r725;
	mov.b32 	{%rs679, %rs680}, %r726;
	mov.b32 	{%rs681, %rs682}, %r735;
	mov.b32 	{%rs683, %rs684}, %r736;
	mov.b32 	{%rs685, %rs686}, %r745;
	mov.b32 	{%rs687, %rs688}, %r746;
	mov.b32 	{%rs689, %rs690}, %r755;
	mov.b32 	{%rs691, %rs692}, %r756;
	mov.b32 	{%rs693, %rs694}, %r765;
	mov.b32 	{%rs695, %rs696}, %r766;
	mov.b32 	{%rs697, %rs698}, %r775;
	mov.b32 	{%rs699, %rs700}, %r776;
	mov.b32 	{%rs701, %rs702}, %r785;
	mov.b32 	{%rs703, %rs704}, %r786;
	mov.b32 	{%rs705, %rs706}, %r795;
	mov.b32 	{%rs707, %rs708}, %r796;
	mov.b32 	{%rs709, %rs710}, %r805;
	mov.b32 	{%rs711, %rs712}, %r806;
	mov.b32 	{%rs713, %rs714}, %r815;
	mov.b32 	{%rs715, %rs716}, %r816;
	mov.b32 	{%rs717, %rs718}, %r825;
	mov.b32 	{%rs719, %rs720}, %r826;
	mov.b32 	{%rs721, %rs722}, %r835;
	mov.b32 	{%rs723, %rs724}, %r836;
	mov.b32 	{%rs725, %rs726}, %r845;
	mov.b32 	{%rs727, %rs728}, %r846;
	mov.b32 	{%rs729, %rs730}, %r855;
	mov.b32 	{%rs731, %rs732}, %r856;
	mov.b32 	{%rs733, %rs734}, %r865;
	mov.b32 	{%rs735, %rs736}, %r866;
	mov.b32 	{%rs737, %rs738}, %r875;
	mov.b32 	{%rs739, %rs740}, %r876;
	mov.b32 	{%rs741, %rs742}, %r885;
	mov.b32 	{%rs743, %rs744}, %r886;
	mov.b32 	{%rs745, %rs746}, %r895;
	mov.b32 	{%rs747, %rs748}, %r896;
	mov.b32 	{%rs749, %rs750}, %r905;
	mov.b32 	{%rs751, %rs752}, %r906;
	mov.b32 	{%rs753, %rs754}, %r915;
	mov.b32 	{%rs755, %rs756}, %r916;
	mov.b32 	{%rs757, %rs758}, %r925;
	mov.b32 	{%rs759, %rs760}, %r926;
	mov.b32 	{%rs761, %rs762}, %r935;
	mov.b32 	{%rs763, %rs764}, %r936;
	mov.b32 	{%rs765, %rs766}, %r945;
	mov.b32 	{%rs767, %rs768}, %r946;
	mov.b32 	{%rs769, %rs770}, %r955;
	mov.b32 	{%rs771, %rs772}, %r956;
	mov.b32 	{%rs773, %rs774}, %r965;
	mov.b32 	{%rs775, %rs776}, %r966;
	mov.b32 	{%rs777, %rs778}, %r975;
	mov.b32 	{%rs779, %rs780}, %r976;
	mov.b32 	{%rs781, %rs782}, %r985;
	mov.b32 	{%rs783, %rs784}, %r986;
	mov.b32 	{%rs785, %rs786}, %r995;
	mov.b32 	{%rs787, %rs788}, %r996;
	.loc	1 102 18
	add.s64 	%rd46, %rd24, %rd103;
	.loc	1 103 18
	add.s64 	%rd47, %rd25, %rd103;
	add.s64 	%rd48, %rd104, %rd14;
	add.s64 	%rd49, %rd104, %rd13;
	add.s64 	%rd50, %rd104, %rd12;
	.loc	1 93 22
	add.s64 	%rd51, %rd104, %rd9;
	add.s32 	%r1201, %r1469, 1;
	setp.lt.s32 	%p35, %r1201, 2;
	selp.b32 	%r1469, %r1201, 0, %p35;
	.loc	1 96 53
	add.s32 	%r1202, %r10, %r1433;
	add.s32 	%r1203, %r1202, 64;
	.loc	1 96 72
	add.s32 	%r1204, %r1202, 80;
	setp.lt.s32 	%p36, %r1203, %r143;
	setp.lt.s32 	%p37, %r1204, %r143;
	.loc	1 96 20
	shl.b32 	%r1205, %r1469, 13;
	add.s32 	%r1207, %r260, %r1205;
	bar.sync 	0;
	add.s32 	%r1005, %r1207, %r259;
	add.s32 	%r1007, %r1207, %r262;
	selp.b32 	%r1210, 16, 0, %p36;
	selp.b32 	%r1006, %r1210, 0, %p34;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r1005 + 0 ], [ %rd46 + 0 ], 0x10, %r1006;
	// end inline asm
	selp.b32 	%r1211, 16, 0, %p37;
	selp.b32 	%r1008, %r1211, 0, %p34;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r1007 + 0 ], [ %rd47 + 0 ], 0x10, %r1008;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 53
	add.s32 	%r1212, %r4, %r1433;
	add.s32 	%r1213, %r1212, 64;
	add.s32 	%r1214, %r1212, 72;
	add.s32 	%r1215, %r1212, 80;
	.loc	1 97 72
	add.s32 	%r1216, %r1212, 88;
	setp.lt.s32 	%p38, %r1213, %r143;
	setp.lt.s32 	%p39, %r1214, %r143;
	setp.lt.s32 	%p40, %r1215, %r143;
	setp.lt.s32 	%p41, %r1216, %r143;
	.loc	1 97 20
	shl.b32 	%r1217, %r1469, 14;
	add.s32 	%r1219, %r268, %r1217;
	add.s32 	%r1009, %r1219, %r267;
	add.s32 	%r1011, %r1219, %r270;
	add.s32 	%r1013, %r1219, %r272;
	add.s32 	%r1015, %r1219, %r274;
	selp.b32 	%r1224, 16, 0, %p38;
	selp.b32 	%r1010, %r1224, 0, %p34;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r1009 + 0 ], [ %rd48 + 0 ], 0x10, %r1010;
	// end inline asm
	selp.b32 	%r1225, 16, 0, %p39;
	selp.b32 	%r1012, %r1225, 0, %p34;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r1011 + 0 ], [ %rd49 + 0 ], 0x10, %r1012;
	// end inline asm
	selp.b32 	%r1226, 16, 0, %p40;
	selp.b32 	%r1014, %r1226, 0, %p34;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r1013 + 0 ], [ %rd50 + 0 ], 0x10, %r1014;
	// end inline asm
	selp.b32 	%r1227, 16, 0, %p41;
	selp.b32 	%r1016, %r1227, 0, %p34;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r1015 + 0 ], [ %rd51 + 0 ], 0x10, %r1016;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1228, %r1468, 1;
	setp.lt.s32 	%p42, %r1228, 2;
	selp.b32 	%r1468, %r1228, 0, %p42;
	.loc	1 96 20
	shl.b32 	%r1229, %r1468, 13;
	add.s32 	%r1467, %r260, %r1229;
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	.loc	1 97 20
	shl.b32 	%r1230, %r1468, 14;
	add.s32 	%r1466, %r268, %r1230;
	.loc	1 96 20
	add.s32 	%r1021, %r1467, %r290;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1462, %r1463, %r1464, %r1465 }, [ %r1021 + 0 ];
	// end inline asm
	add.s32 	%r1026, %r1467, %r294;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1458, %r1459, %r1460, %r1461 }, [ %r1026 + 0 ];
	// end inline asm
	add.s32 	%r1031, %r1467, %r298;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1454, %r1455, %r1456, %r1457 }, [ %r1031 + 0 ];
	// end inline asm
	add.s32 	%r1036, %r1467, %r302;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1450, %r1451, %r1452, %r1453 }, [ %r1036 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r1041, %r1466, %r308;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1446, %r1447, %r1448, %r1449 }, [ %r1041 + 0 ];
	// end inline asm
	add.s32 	%r1046, %r1466, %r312;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1442, %r1443, %r1444, %r1445 }, [ %r1046 + 0 ];
	// end inline asm
	add.s32 	%r1051, %r1466, %r316;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1438, %r1439, %r1440, %r1441 }, [ %r1051 + 0 ];
	// end inline asm
	add.s32 	%r1056, %r1466, %r320;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1434, %r1435, %r1436, %r1437 }, [ %r1056 + 0 ];
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1470, %r1470, 1;
	add.s64 	%rd104, %rd104, %rd11;
	add.s64 	%rd103, %rd103, %rd16;
	add.s32 	%r1433, %r1433, 32;
	setp.lt.s32 	%p43, %r1470, %r11;
	@%p43 bra 	$L__BB0_2;
$L__BB0_3:
	.loc	1 74 51
	or.b32  	%r1295, %r1, %r4;
	.loc	1 74 38
	or.b32  	%r1296, %r1295, 120;
	.loc	1 83 33
	setp.lt.s32 	%p62, %r1296, %r141;
	.loc	1 83 58
	setp.lt.s32 	%p63, %r9, %r142;
	.loc	1 83 39
	and.pred  	%p61, %p62, %p63;
	.loc	1 74 38
	or.b32  	%r1297, %r1295, 112;
	.loc	1 83 33
	setp.lt.s32 	%p64, %r1297, %r141;
	.loc	1 83 39
	and.pred  	%p60, %p64, %p63;
	.loc	1 74 38
	or.b32  	%r1298, %r1295, 104;
	.loc	1 83 33
	setp.lt.s32 	%p65, %r1298, %r141;
	.loc	1 83 39
	and.pred  	%p59, %p65, %p63;
	.loc	1 74 38
	or.b32  	%r1299, %r1295, 96;
	.loc	1 83 33
	setp.lt.s32 	%p66, %r1299, %r141;
	.loc	1 83 39
	and.pred  	%p58, %p66, %p63;
	.loc	1 74 38
	or.b32  	%r1300, %r1295, 88;
	.loc	1 83 33
	setp.lt.s32 	%p67, %r1300, %r141;
	.loc	1 83 39
	and.pred  	%p57, %p67, %p63;
	.loc	1 74 38
	or.b32  	%r1301, %r1295, 80;
	.loc	1 83 33
	setp.lt.s32 	%p68, %r1301, %r141;
	.loc	1 83 39
	and.pred  	%p56, %p68, %p63;
	.loc	1 74 38
	or.b32  	%r1302, %r1295, 72;
	.loc	1 83 33
	setp.lt.s32 	%p69, %r1302, %r141;
	.loc	1 83 39
	and.pred  	%p55, %p69, %p63;
	.loc	1 74 38
	or.b32  	%r1303, %r1295, 64;
	.loc	1 83 33
	setp.lt.s32 	%p70, %r1303, %r141;
	.loc	1 83 39
	and.pred  	%p54, %p70, %p63;
	.loc	1 74 38
	or.b32  	%r1304, %r1, %r21;
	.loc	1 83 33
	setp.lt.s32 	%p71, %r1304, %r141;
	.loc	1 83 39
	and.pred  	%p53, %p71, %p63;
	.loc	1 74 38
	or.b32  	%r1305, %r1, %r20;
	.loc	1 83 33
	setp.lt.s32 	%p72, %r1305, %r141;
	.loc	1 83 39
	and.pred  	%p52, %p72, %p63;
	.loc	1 74 38
	or.b32  	%r1306, %r1, %r19;
	.loc	1 83 33
	setp.lt.s32 	%p73, %r1306, %r141;
	.loc	1 83 39
	and.pred  	%p51, %p73, %p63;
	.loc	1 74 38
	or.b32  	%r1307, %r1, %r18;
	.loc	1 83 33
	setp.lt.s32 	%p74, %r1307, %r141;
	.loc	1 83 39
	and.pred  	%p50, %p74, %p63;
	.loc	1 74 38
	or.b32  	%r1308, %r1, %r7;
	.loc	1 83 33
	setp.lt.s32 	%p75, %r1308, %r141;
	.loc	1 83 39
	and.pred  	%p49, %p75, %p63;
	.loc	1 74 38
	or.b32  	%r1309, %r1, %r6;
	.loc	1 83 33
	setp.lt.s32 	%p76, %r1309, %r141;
	.loc	1 83 39
	and.pred  	%p48, %p76, %p63;
	.loc	1 74 38
	or.b32  	%r1310, %r1, %r5;
	.loc	1 83 33
	setp.lt.s32 	%p77, %r1310, %r141;
	.loc	1 83 39
	and.pred  	%p47, %p77, %p63;
	.loc	1 83 33
	setp.lt.s32 	%p78, %r1295, %r141;
	.loc	1 83 39
	and.pred  	%p46, %p78, %p63;
	.loc	1 82 33
	mul.lo.s32 	%r1311, %r1296, %r144;
	.loc	1 82 21
	mul.wide.s32 	%rd69, %r1311, 2;
	add.s64 	%rd70, %rd22, %rd69;
	.loc	1 82 52
	mul.wide.s32 	%rd71, %r9, 2;
	add.s64 	%rd68, %rd70, %rd71;
	.loc	1 82 33
	shl.b32 	%r1312, %r144, 3;
	sub.s32 	%r1313, %r1311, %r1312;
	.loc	1 82 21
	mul.wide.s32 	%rd72, %r1313, 2;
	add.s64 	%rd73, %rd22, %rd72;
	.loc	1 82 52
	add.s64 	%rd67, %rd73, %rd71;
	.loc	1 82 33
	sub.s32 	%r1314, %r1313, %r1312;
	.loc	1 82 21
	mul.wide.s32 	%rd74, %r1314, 2;
	add.s64 	%rd75, %rd22, %rd74;
	.loc	1 82 52
	add.s64 	%rd66, %rd75, %rd71;
	.loc	1 82 33
	sub.s32 	%r1315, %r1314, %r1312;
	.loc	1 82 21
	mul.wide.s32 	%rd76, %r1315, 2;
	add.s64 	%rd77, %rd22, %rd76;
	.loc	1 82 52
	add.s64 	%rd65, %rd77, %rd71;
	.loc	1 82 33
	sub.s32 	%r1316, %r1315, %r1312;
	.loc	1 82 21
	mul.wide.s32 	%rd78, %r1316, 2;
	add.s64 	%rd79, %rd22, %rd78;
	.loc	1 82 52
	add.s64 	%rd64, %rd79, %rd71;
	.loc	1 82 33
	sub.s32 	%r1317, %r1316, %r1312;
	.loc	1 82 21
	mul.wide.s32 	%rd80, %r1317, 2;
	add.s64 	%rd81, %rd22, %rd80;
	.loc	1 82 52
	add.s64 	%rd63, %rd81, %rd71;
	.loc	1 82 33
	sub.s32 	%r1318, %r1317, %r1312;
	.loc	1 82 21
	mul.wide.s32 	%rd82, %r1318, 2;
	add.s64 	%rd83, %rd22, %rd82;
	.loc	1 82 52
	add.s64 	%rd62, %rd83, %rd71;
	.loc	1 82 33
	sub.s32 	%r1319, %r1318, %r1312;
	.loc	1 82 21
	mul.wide.s32 	%rd84, %r1319, 2;
	add.s64 	%rd85, %rd22, %rd84;
	.loc	1 82 52
	add.s64 	%rd61, %rd85, %rd71;
	.loc	1 82 33
	mul.lo.s32 	%r1320, %r1304, %r144;
	.loc	1 82 21
	mul.wide.s32 	%rd86, %r1320, 2;
	add.s64 	%rd87, %rd22, %rd86;
	.loc	1 82 52
	add.s64 	%rd60, %rd87, %rd71;
	.loc	1 82 33
	mul.lo.s32 	%r1321, %r1305, %r144;
	.loc	1 82 21
	mul.wide.s32 	%rd88, %r1321, 2;
	add.s64 	%rd89, %rd22, %rd88;
	.loc	1 82 52
	add.s64 	%rd59, %rd89, %rd71;
	.loc	1 82 33
	mul.lo.s32 	%r1322, %r1306, %r144;
	.loc	1 82 21
	mul.wide.s32 	%rd90, %r1322, 2;
	add.s64 	%rd91, %rd22, %rd90;
	.loc	1 82 52
	add.s64 	%rd58, %rd91, %rd71;
	.loc	1 82 33
	mul.lo.s32 	%r1323, %r1307, %r144;
	.loc	1 82 21
	mul.wide.s32 	%rd92, %r1323, 2;
	add.s64 	%rd93, %rd22, %rd92;
	.loc	1 82 52
	add.s64 	%rd57, %rd93, %rd71;
	.loc	1 82 33
	mul.lo.s32 	%r1324, %r1308, %r144;
	.loc	1 82 21
	mul.wide.s32 	%rd94, %r1324, 2;
	add.s64 	%rd95, %rd22, %rd94;
	.loc	1 82 52
	add.s64 	%rd56, %rd95, %rd71;
	.loc	1 82 33
	mul.lo.s32 	%r1325, %r1309, %r144;
	.loc	1 82 21
	mul.wide.s32 	%rd96, %r1325, 2;
	add.s64 	%rd97, %rd22, %rd96;
	.loc	1 82 52
	add.s64 	%rd55, %rd97, %rd71;
	.loc	1 82 33
	mul.lo.s32 	%r1326, %r1310, %r144;
	.loc	1 82 21
	mul.wide.s32 	%rd98, %r1326, 2;
	add.s64 	%rd99, %rd22, %rd98;
	.loc	1 82 52
	add.s64 	%rd54, %rd99, %rd71;
	.loc	1 82 33
	mul.lo.s32 	%r1327, %r1295, %r144;
	.loc	1 82 21
	mul.wide.s32 	%rd100, %r1327, 2;
	add.s64 	%rd101, %rd22, %rd100;
	.loc	1 82 52
	add.s64 	%rd53, %rd101, %rd71;
	.loc	1 75 51
	and.b32  	%r1328, %r2, 255;
	.loc	1 75 38
	or.b32  	%r1329, %r8, %r1328;
	.loc	1 93 22
	// begin inline asm
	cp.async.wait_group 0x0;
	// end inline asm
	bar.sync 	0;
	.loc	1 107 31
	mul.wide.s32 	%rd102, %r1329, 2;
	add.s64 	%rd52, %rd23, %rd102;
	.loc	1 108 32
	setp.lt.s32 	%p44, %r1329, %r142;
	mov.u16 	%rs388, 0;
	.loc	1 109 23
	// begin inline asm
	mov.u16 %rs387, 0x0;
	@%p44 ld.global.b16 { %rs387 }, [ %rd52 + 0 ];
	@!%p44 mov.u16 %rs387, %rs388;
	// end inline asm
	.loc	1 110 30
	shl.b32 	%r1330, %r1328, 1;
	add.s32 	%r1332, %r260, %r1330;
	st.shared.u16 	[%r1332], %rs387;
	bar.sync 	0;
	shl.b32 	%r1333, %r43, 4;
	shl.b32 	%r1334, %r2, 2;
	and.b32  	%r1335, %r1334, 12;
	or.b32  	%r1336, %r1333, %r1335;
	add.s32 	%r1337, %r260, %r1336;
	ld.shared.b32 	%r1338, [%r1337];
	mov.b32 	{%rs389, %rs390}, %r1338;
	add.s32 	%r1339, %r1337, 64;
	ld.shared.b32 	%r1340, [%r1337+64];
	mov.b32 	{%rs391, %rs392}, %r1340;
	add.s32 	%r1341, %r1337, 128;
	ld.shared.b32 	%r1342, [%r1337+128];
	mov.b32 	{%rs393, %rs394}, %r1342;
	add.s32 	%r1343, %r1337, 192;
	ld.shared.b32 	%r1344, [%r1337+192];
	mov.b32 	{%rs395, %rs396}, %r1344;
	add.s32 	%r1345, %r1337, 256;
	ld.shared.b32 	%r1346, [%r1337+256];
	mov.b32 	{%rs397, %rs398}, %r1346;
	add.s32 	%r1347, %r1337, 320;
	ld.shared.b32 	%r1348, [%r1337+320];
	mov.b32 	{%rs399, %rs400}, %r1348;
	add.s32 	%r1349, %r1337, 384;
	ld.shared.b32 	%r1350, [%r1337+384];
	mov.b32 	{%rs401, %rs402}, %r1350;
	add.s32 	%r1351, %r1337, 448;
	ld.shared.b32 	%r1352, [%r1337+448];
	mov.b32 	{%rs403, %rs404}, %r1352;
	.loc	1 111 23
	add.f16 	%rs405, %rs661, %rs389;
	add.f16 	%rs406, %rs662, %rs390;
	add.f16 	%rs407, %rs663, %rs389;
	add.f16 	%rs408, %rs664, %rs390;
	add.f16 	%rs409, %rs665, %rs391;
	add.f16 	%rs410, %rs666, %rs392;
	add.f16 	%rs411, %rs667, %rs391;
	add.f16 	%rs412, %rs668, %rs392;
	add.f16 	%rs413, %rs669, %rs393;
	add.f16 	%rs414, %rs670, %rs394;
	add.f16 	%rs415, %rs671, %rs393;
	add.f16 	%rs416, %rs672, %rs394;
	add.f16 	%rs417, %rs673, %rs395;
	add.f16 	%rs418, %rs674, %rs396;
	add.f16 	%rs419, %rs675, %rs395;
	add.f16 	%rs420, %rs676, %rs396;
	add.f16 	%rs421, %rs677, %rs397;
	add.f16 	%rs422, %rs678, %rs398;
	add.f16 	%rs423, %rs679, %rs397;
	add.f16 	%rs424, %rs680, %rs398;
	add.f16 	%rs425, %rs681, %rs399;
	add.f16 	%rs426, %rs682, %rs400;
	add.f16 	%rs427, %rs683, %rs399;
	add.f16 	%rs428, %rs684, %rs400;
	add.f16 	%rs429, %rs685, %rs401;
	add.f16 	%rs430, %rs686, %rs402;
	add.f16 	%rs431, %rs687, %rs401;
	add.f16 	%rs432, %rs688, %rs402;
	add.f16 	%rs433, %rs689, %rs403;
	add.f16 	%rs434, %rs690, %rs404;
	add.f16 	%rs435, %rs691, %rs403;
	add.f16 	%rs436, %rs692, %rs404;
	add.f16 	%rs437, %rs693, %rs389;
	add.f16 	%rs438, %rs694, %rs390;
	add.f16 	%rs439, %rs695, %rs389;
	add.f16 	%rs440, %rs696, %rs390;
	add.f16 	%rs441, %rs697, %rs391;
	add.f16 	%rs442, %rs698, %rs392;
	add.f16 	%rs443, %rs699, %rs391;
	add.f16 	%rs444, %rs700, %rs392;
	add.f16 	%rs445, %rs701, %rs393;
	add.f16 	%rs446, %rs702, %rs394;
	add.f16 	%rs447, %rs703, %rs393;
	add.f16 	%rs448, %rs704, %rs394;
	add.f16 	%rs449, %rs705, %rs395;
	add.f16 	%rs450, %rs706, %rs396;
	add.f16 	%rs451, %rs707, %rs395;
	add.f16 	%rs452, %rs708, %rs396;
	add.f16 	%rs453, %rs709, %rs397;
	add.f16 	%rs454, %rs710, %rs398;
	add.f16 	%rs455, %rs711, %rs397;
	add.f16 	%rs456, %rs712, %rs398;
	add.f16 	%rs457, %rs713, %rs399;
	add.f16 	%rs458, %rs714, %rs400;
	add.f16 	%rs459, %rs715, %rs399;
	add.f16 	%rs460, %rs716, %rs400;
	add.f16 	%rs461, %rs717, %rs401;
	add.f16 	%rs462, %rs718, %rs402;
	add.f16 	%rs463, %rs719, %rs401;
	add.f16 	%rs464, %rs720, %rs402;
	add.f16 	%rs465, %rs721, %rs403;
	add.f16 	%rs466, %rs722, %rs404;
	add.f16 	%rs467, %rs723, %rs403;
	add.f16 	%rs468, %rs724, %rs404;
	add.f16 	%rs469, %rs725, %rs389;
	add.f16 	%rs470, %rs726, %rs390;
	add.f16 	%rs471, %rs727, %rs389;
	add.f16 	%rs472, %rs728, %rs390;
	add.f16 	%rs473, %rs729, %rs391;
	add.f16 	%rs474, %rs730, %rs392;
	add.f16 	%rs475, %rs731, %rs391;
	add.f16 	%rs476, %rs732, %rs392;
	add.f16 	%rs477, %rs733, %rs393;
	add.f16 	%rs478, %rs734, %rs394;
	add.f16 	%rs479, %rs735, %rs393;
	add.f16 	%rs480, %rs736, %rs394;
	add.f16 	%rs481, %rs737, %rs395;
	add.f16 	%rs482, %rs738, %rs396;
	add.f16 	%rs483, %rs739, %rs395;
	add.f16 	%rs484, %rs740, %rs396;
	add.f16 	%rs485, %rs741, %rs397;
	add.f16 	%rs486, %rs742, %rs398;
	add.f16 	%rs487, %rs743, %rs397;
	add.f16 	%rs488, %rs744, %rs398;
	add.f16 	%rs489, %rs745, %rs399;
	add.f16 	%rs490, %rs746, %rs400;
	add.f16 	%rs491, %rs747, %rs399;
	add.f16 	%rs492, %rs748, %rs400;
	add.f16 	%rs493, %rs749, %rs401;
	add.f16 	%rs494, %rs750, %rs402;
	add.f16 	%rs495, %rs751, %rs401;
	add.f16 	%rs496, %rs752, %rs402;
	add.f16 	%rs497, %rs753, %rs403;
	add.f16 	%rs498, %rs754, %rs404;
	add.f16 	%rs499, %rs755, %rs403;
	add.f16 	%rs500, %rs756, %rs404;
	add.f16 	%rs501, %rs757, %rs389;
	add.f16 	%rs502, %rs758, %rs390;
	add.f16 	%rs503, %rs759, %rs389;
	add.f16 	%rs504, %rs760, %rs390;
	add.f16 	%rs505, %rs761, %rs391;
	add.f16 	%rs506, %rs762, %rs392;
	add.f16 	%rs507, %rs763, %rs391;
	add.f16 	%rs508, %rs764, %rs392;
	add.f16 	%rs509, %rs765, %rs393;
	add.f16 	%rs510, %rs766, %rs394;
	add.f16 	%rs511, %rs767, %rs393;
	add.f16 	%rs512, %rs768, %rs394;
	add.f16 	%rs513, %rs769, %rs395;
	add.f16 	%rs514, %rs770, %rs396;
	add.f16 	%rs515, %rs771, %rs395;
	add.f16 	%rs516, %rs772, %rs396;
	add.f16 	%rs517, %rs773, %rs397;
	add.f16 	%rs518, %rs774, %rs398;
	add.f16 	%rs519, %rs775, %rs397;
	add.f16 	%rs520, %rs776, %rs398;
	add.f16 	%rs521, %rs777, %rs399;
	add.f16 	%rs522, %rs778, %rs400;
	add.f16 	%rs523, %rs779, %rs399;
	add.f16 	%rs524, %rs780, %rs400;
	add.f16 	%rs525, %rs781, %rs401;
	add.f16 	%rs526, %rs782, %rs402;
	add.f16 	%rs527, %rs783, %rs401;
	add.f16 	%rs528, %rs784, %rs402;
	add.f16 	%rs529, %rs785, %rs403;
	add.f16 	%rs530, %rs786, %rs404;
	add.f16 	%rs531, %rs787, %rs403;
	add.f16 	%rs532, %rs788, %rs404;
	.loc	1 128 21
	bar.sync 	0;
	shr.u32 	%r1353, %r3, 2;
	shl.b32 	%r1354, %r22, 4;
	or.b32  	%r1355, %r1354, %r1353;
	mul.lo.s32 	%r1356, %r1355, 528;
	add.s32 	%r1357, %r1337, %r1356;
	mov.b32 	%r1358, {%rs405, %rs406};
	st.shared.b32 	[%r1357], %r1358;
	mov.b32 	%r1359, {%rs407, %rs408};
	st.shared.b32 	[%r1357+4224], %r1359;
	mov.b32 	%r1360, {%rs409, %rs410};
	st.shared.b32 	[%r1357+64], %r1360;
	add.s32 	%r1361, %r1339, %r1356;
	mov.b32 	%r1362, {%rs411, %rs412};
	st.shared.b32 	[%r1361+4224], %r1362;
	mov.b32 	%r1363, {%rs413, %rs414};
	st.shared.b32 	[%r1357+128], %r1363;
	add.s32 	%r1364, %r1341, %r1356;
	mov.b32 	%r1365, {%rs415, %rs416};
	st.shared.b32 	[%r1364+4224], %r1365;
	mov.b32 	%r1366, {%rs417, %rs418};
	st.shared.b32 	[%r1357+192], %r1366;
	add.s32 	%r1367, %r1343, %r1356;
	mov.b32 	%r1368, {%rs419, %rs420};
	st.shared.b32 	[%r1367+4224], %r1368;
	mov.b32 	%r1369, {%rs421, %rs422};
	st.shared.b32 	[%r1357+256], %r1369;
	add.s32 	%r1370, %r1345, %r1356;
	mov.b32 	%r1371, {%rs423, %rs424};
	st.shared.b32 	[%r1370+4224], %r1371;
	mov.b32 	%r1372, {%rs425, %rs426};
	st.shared.b32 	[%r1357+320], %r1372;
	add.s32 	%r1373, %r1347, %r1356;
	mov.b32 	%r1374, {%rs427, %rs428};
	st.shared.b32 	[%r1373+4224], %r1374;
	mov.b32 	%r1375, {%rs429, %rs430};
	st.shared.b32 	[%r1357+384], %r1375;
	add.s32 	%r1376, %r1349, %r1356;
	mov.b32 	%r1377, {%rs431, %rs432};
	st.shared.b32 	[%r1376+4224], %r1377;
	mov.b32 	%r1378, {%rs433, %rs434};
	st.shared.b32 	[%r1357+448], %r1378;
	add.s32 	%r1379, %r1351, %r1356;
	mov.b32 	%r1380, {%rs435, %rs436};
	st.shared.b32 	[%r1379+4224], %r1380;
	bar.sync 	0;
	shl.b32 	%r1381, %r3, 3;
	mad.lo.s32 	%r1382, %r4, 264, %r1381;
	shl.b32 	%r1383, %r1382, 1;
	add.s32 	%r1384, %r260, %r1383;
	ld.shared.v4.u32 	{%r1231, %r1232, %r1233, %r1234}, [%r1384];
	ld.shared.v4.u32 	{%r1235, %r1236, %r1237, %r1238}, [%r1384+4224];
	ld.shared.v4.u32 	{%r1239, %r1240, %r1241, %r1242}, [%r1384+8448];
	ld.shared.v4.u32 	{%r1243, %r1244, %r1245, %r1246}, [%r1384+12672];
	bar.sync 	0;
	mov.b32 	%r1385, {%rs437, %rs438};
	st.shared.b32 	[%r1357], %r1385;
	mov.b32 	%r1386, {%rs439, %rs440};
	st.shared.b32 	[%r1357+4224], %r1386;
	mov.b32 	%r1387, {%rs441, %rs442};
	st.shared.b32 	[%r1357+64], %r1387;
	mov.b32 	%r1388, {%rs443, %rs444};
	st.shared.b32 	[%r1361+4224], %r1388;
	mov.b32 	%r1389, {%rs445, %rs446};
	st.shared.b32 	[%r1357+128], %r1389;
	mov.b32 	%r1390, {%rs447, %rs448};
	st.shared.b32 	[%r1364+4224], %r1390;
	mov.b32 	%r1391, {%rs449, %rs450};
	st.shared.b32 	[%r1357+192], %r1391;
	mov.b32 	%r1392, {%rs451, %rs452};
	st.shared.b32 	[%r1367+4224], %r1392;
	mov.b32 	%r1393, {%rs453, %rs454};
	st.shared.b32 	[%r1357+256], %r1393;
	mov.b32 	%r1394, {%rs455, %rs456};
	st.shared.b32 	[%r1370+4224], %r1394;
	mov.b32 	%r1395, {%rs457, %rs458};
	st.shared.b32 	[%r1357+320], %r1395;
	mov.b32 	%r1396, {%rs459, %rs460};
	st.shared.b32 	[%r1373+4224], %r1396;
	mov.b32 	%r1397, {%rs461, %rs462};
	st.shared.b32 	[%r1357+384], %r1397;
	mov.b32 	%r1398, {%rs463, %rs464};
	st.shared.b32 	[%r1376+4224], %r1398;
	mov.b32 	%r1399, {%rs465, %rs466};
	st.shared.b32 	[%r1357+448], %r1399;
	mov.b32 	%r1400, {%rs467, %rs468};
	st.shared.b32 	[%r1379+4224], %r1400;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1247, %r1248, %r1249, %r1250}, [%r1384];
	ld.shared.v4.u32 	{%r1251, %r1252, %r1253, %r1254}, [%r1384+4224];
	ld.shared.v4.u32 	{%r1255, %r1256, %r1257, %r1258}, [%r1384+8448];
	ld.shared.v4.u32 	{%r1259, %r1260, %r1261, %r1262}, [%r1384+12672];
	bar.sync 	0;
	mov.b32 	%r1401, {%rs469, %rs470};
	st.shared.b32 	[%r1357], %r1401;
	mov.b32 	%r1402, {%rs471, %rs472};
	st.shared.b32 	[%r1357+4224], %r1402;
	mov.b32 	%r1403, {%rs473, %rs474};
	st.shared.b32 	[%r1357+64], %r1403;
	mov.b32 	%r1404, {%rs475, %rs476};
	st.shared.b32 	[%r1361+4224], %r1404;
	mov.b32 	%r1405, {%rs477, %rs478};
	st.shared.b32 	[%r1357+128], %r1405;
	mov.b32 	%r1406, {%rs479, %rs480};
	st.shared.b32 	[%r1364+4224], %r1406;
	mov.b32 	%r1407, {%rs481, %rs482};
	st.shared.b32 	[%r1357+192], %r1407;
	mov.b32 	%r1408, {%rs483, %rs484};
	st.shared.b32 	[%r1367+4224], %r1408;
	mov.b32 	%r1409, {%rs485, %rs486};
	st.shared.b32 	[%r1357+256], %r1409;
	mov.b32 	%r1410, {%rs487, %rs488};
	st.shared.b32 	[%r1370+4224], %r1410;
	mov.b32 	%r1411, {%rs489, %rs490};
	st.shared.b32 	[%r1357+320], %r1411;
	mov.b32 	%r1412, {%rs491, %rs492};
	st.shared.b32 	[%r1373+4224], %r1412;
	mov.b32 	%r1413, {%rs493, %rs494};
	st.shared.b32 	[%r1357+384], %r1413;
	mov.b32 	%r1414, {%rs495, %rs496};
	st.shared.b32 	[%r1376+4224], %r1414;
	mov.b32 	%r1415, {%rs497, %rs498};
	st.shared.b32 	[%r1357+448], %r1415;
	mov.b32 	%r1416, {%rs499, %rs500};
	st.shared.b32 	[%r1379+4224], %r1416;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1263, %r1264, %r1265, %r1266}, [%r1384];
	ld.shared.v4.u32 	{%r1267, %r1268, %r1269, %r1270}, [%r1384+4224];
	ld.shared.v4.u32 	{%r1271, %r1272, %r1273, %r1274}, [%r1384+8448];
	ld.shared.v4.u32 	{%r1275, %r1276, %r1277, %r1278}, [%r1384+12672];
	bar.sync 	0;
	mov.b32 	%r1417, {%rs501, %rs502};
	st.shared.b32 	[%r1357], %r1417;
	mov.b32 	%r1418, {%rs503, %rs504};
	st.shared.b32 	[%r1357+4224], %r1418;
	mov.b32 	%r1419, {%rs505, %rs506};
	st.shared.b32 	[%r1357+64], %r1419;
	mov.b32 	%r1420, {%rs507, %rs508};
	st.shared.b32 	[%r1361+4224], %r1420;
	mov.b32 	%r1421, {%rs509, %rs510};
	st.shared.b32 	[%r1357+128], %r1421;
	mov.b32 	%r1422, {%rs511, %rs512};
	st.shared.b32 	[%r1364+4224], %r1422;
	mov.b32 	%r1423, {%rs513, %rs514};
	st.shared.b32 	[%r1357+192], %r1423;
	mov.b32 	%r1424, {%rs515, %rs516};
	st.shared.b32 	[%r1367+4224], %r1424;
	mov.b32 	%r1425, {%rs517, %rs518};
	st.shared.b32 	[%r1357+256], %r1425;
	mov.b32 	%r1426, {%rs519, %rs520};
	st.shared.b32 	[%r1370+4224], %r1426;
	mov.b32 	%r1427, {%rs521, %rs522};
	st.shared.b32 	[%r1357+320], %r1427;
	mov.b32 	%r1428, {%rs523, %rs524};
	st.shared.b32 	[%r1373+4224], %r1428;
	mov.b32 	%r1429, {%rs525, %rs526};
	st.shared.b32 	[%r1357+384], %r1429;
	mov.b32 	%r1430, {%rs527, %rs528};
	st.shared.b32 	[%r1376+4224], %r1430;
	mov.b32 	%r1431, {%rs529, %rs530};
	st.shared.b32 	[%r1357+448], %r1431;
	mov.b32 	%r1432, {%rs531, %rs532};
	st.shared.b32 	[%r1379+4224], %r1432;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1279, %r1280, %r1281, %r1282}, [%r1384];
	ld.shared.v4.u32 	{%r1283, %r1284, %r1285, %r1286}, [%r1384+4224];
	ld.shared.v4.u32 	{%r1287, %r1288, %r1289, %r1290}, [%r1384+8448];
	ld.shared.v4.u32 	{%r1291, %r1292, %r1293, %r1294}, [%r1384+12672];
	// begin inline asm
	@%p46 st.global.v4.b32 [ %rd53 + 0 ], { %r1231, %r1232, %r1233, %r1234 };
	// end inline asm
	// begin inline asm
	@%p47 st.global.v4.b32 [ %rd54 + 0 ], { %r1235, %r1236, %r1237, %r1238 };
	// end inline asm
	// begin inline asm
	@%p48 st.global.v4.b32 [ %rd55 + 0 ], { %r1239, %r1240, %r1241, %r1242 };
	// end inline asm
	// begin inline asm
	@%p49 st.global.v4.b32 [ %rd56 + 0 ], { %r1243, %r1244, %r1245, %r1246 };
	// end inline asm
	// begin inline asm
	@%p50 st.global.v4.b32 [ %rd57 + 0 ], { %r1247, %r1248, %r1249, %r1250 };
	// end inline asm
	// begin inline asm
	@%p51 st.global.v4.b32 [ %rd58 + 0 ], { %r1251, %r1252, %r1253, %r1254 };
	// end inline asm
	// begin inline asm
	@%p52 st.global.v4.b32 [ %rd59 + 0 ], { %r1255, %r1256, %r1257, %r1258 };
	// end inline asm
	// begin inline asm
	@%p53 st.global.v4.b32 [ %rd60 + 0 ], { %r1259, %r1260, %r1261, %r1262 };
	// end inline asm
	// begin inline asm
	@%p54 st.global.v4.b32 [ %rd61 + 0 ], { %r1263, %r1264, %r1265, %r1266 };
	// end inline asm
	// begin inline asm
	@%p55 st.global.v4.b32 [ %rd62 + 0 ], { %r1267, %r1268, %r1269, %r1270 };
	// end inline asm
	// begin inline asm
	@%p56 st.global.v4.b32 [ %rd63 + 0 ], { %r1271, %r1272, %r1273, %r1274 };
	// end inline asm
	// begin inline asm
	@%p57 st.global.v4.b32 [ %rd64 + 0 ], { %r1275, %r1276, %r1277, %r1278 };
	// end inline asm
	// begin inline asm
	@%p58 st.global.v4.b32 [ %rd65 + 0 ], { %r1279, %r1280, %r1281, %r1282 };
	// end inline asm
	// begin inline asm
	@%p59 st.global.v4.b32 [ %rd66 + 0 ], { %r1283, %r1284, %r1285, %r1286 };
	// end inline asm
	// begin inline asm
	@%p60 st.global.v4.b32 [ %rd67 + 0 ], { %r1287, %r1288, %r1289, %r1290 };
	// end inline asm
	// begin inline asm
	@%p61 st.global.v4.b32 [ %rd68 + 0 ], { %r1291, %r1292, %r1293, %r1294 };
	// end inline asm
	.loc	1 128 4
	ret;
$L__tmp6:
$L__func_end0:

}
	.file	1 "/home/mike/Desktop/Descite/llm.c/dev/triton/compile_matmul_kernel_bias_transpose_a.py"
	.file	2 "/home/mike/Desktop/Descite/llm.c/venv/lib/python3.12/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1
.b8 17
.b8 1
.b8 37
.b8 8
.b8 19
.b8 5
.b8 3
.b8 8
.b8 16
.b8 6
.b8 27
.b8 8
.b8 17
.b8 1
.b8 18
.b8 1
.b8 0
.b8 0
.b8 2
.b8 46
.b8 0
.b8 3
.b8 8
.b8 32
.b8 11
.b8 0
.b8 0
.b8 3
.b8 46
.b8 1
.b8 17
.b8 1
.b8 18
.b8 1
.b8 49
.b8 19
.b8 0
.b8 0
.b8 4
.b8 29
.b8 0
.b8 49
.b8 19
.b8 17
.b8 1
.b8 18
.b8 1
.b8 88
.b8 11
.b8 89
.b8 11
.b8 87
.b8 11
.b8 0
.b8 0
.b8 0
	}
	.section	.debug_info
	{
.b32 217
.b8 2
.b8 0
.b32 .debug_abbrev
.b8 8
.b8 1
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2
.b8 0
.b8 99
.b8 111
.b8 109
.b8 112
.b8 105
.b8 108
.b8 101
.b8 95
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 109
.b8 105
.b8 107
.b8 101
.b8 47
.b8 68
.b8 101
.b8 115
.b8 107
.b8 116
.b8 111
.b8 112
.b8 47
.b8 68
.b8 101
.b8 115
.b8 99
.b8 105
.b8 116
.b8 101
.b8 47
.b8 108
.b8 108
.b8 109
.b8 46
.b8 99
.b8 47
.b8 100
.b8 101
.b8 118
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b64 $L__func_begin0
.b64 $L__func_end0
.b8 2
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1
.b8 3
.b64 $L__func_begin0
.b64 $L__func_end0
.b32 110
.b8 4
.b32 110
.b64 $L__tmp1
.b64 $L__tmp2
.b8 1
.b8 58
.b8 27
.b8 4
.b32 110
.b64 $L__tmp2
.b64 $L__tmp3
.b8 1
.b8 59
.b8 27
.b8 4
.b32 110
.b64 $L__tmp4
.b64 $L__tmp5
.b8 1
.b8 93
.b8 33
.b8 0
.b8 0
	}
	.section	.debug_loc	{	}
)";

#define TRITON_MATMUL_KERNEL_10_SHARED_MEMORY_SIZE 49152
#define TRITON_MATMUL_KERNEL_10_BLOCK_SIZE_M 128
#define TRITON_MATMUL_KERNEL_10_BLOCK_SIZE_N 256
#define TRITON_MATMUL_KERNEL_10_NUM_WARPS 8
#define TRITON_MATMUL_KERNEL_10_FUNCTION_NAME "matmul_kernel_bias_transpose_a"
