/*
 * WARNING: This is an autogenerated file. DO NOT EDIT.
 * This file was generated by generate_kernels.sh which intern launches compile_matmul_kernel.py */
#pragma once

#include <string>

const std::string TRITON_MATMUL_KERNEL_8_SOURCE_PTX = R"(
//
// Generated by LLVM NVPTX Back-End
//

.version 8.4
.target sm_89
.address_size 64

	// .globl	matmul_kernel_bias
.extern .shared .align 16 .b8 global_smem[];

.visible .entry matmul_kernel_bias(
	.param .u64 matmul_kernel_bias_param_0,
	.param .u64 matmul_kernel_bias_param_1,
	.param .u64 matmul_kernel_bias_param_2,
	.param .u64 matmul_kernel_bias_param_3,
	.param .u32 matmul_kernel_bias_param_4,
	.param .u32 matmul_kernel_bias_param_5,
	.param .u32 matmul_kernel_bias_param_6,
	.param .u32 matmul_kernel_bias_param_7,
	.param .u32 matmul_kernel_bias_param_8,
	.param .u32 matmul_kernel_bias_param_9
)
.maxntid 256, 1, 1
{
	.reg .pred 	%p<76>;
	.reg .b16 	%rs<789>;
	.reg .b32 	%r<1447>;
	.reg .b64 	%rd<110>;
	.loc	1 41 0
$L__func_begin0:
	.loc	1 41 0

	ld.param.u32 	%r146, [matmul_kernel_bias_param_9];
	ld.param.u32 	%r145, [matmul_kernel_bias_param_6];
	ld.param.u32 	%r144, [matmul_kernel_bias_param_5];
	ld.param.u32 	%r143, [matmul_kernel_bias_param_4];
	ld.param.u64 	%rd25, [matmul_kernel_bias_param_3];
	ld.param.u64 	%rd24, [matmul_kernel_bias_param_2];
	ld.param.u64 	%rd23, [matmul_kernel_bias_param_1];
	ld.param.u64 	%rd22, [matmul_kernel_bias_param_0];
$L__tmp0:
	.loc	1 57 24
	// begin inline asm
	mov.u32 %r147, %ctaid.x;
	// end inline asm
$L__tmp1:
	.loc	2 44 22
	add.s32 	%r212, %r143, 127;
	.loc	2 44 28
	shr.s32 	%r213, %r212, 31;
	shr.u32 	%r214, %r213, 25;
	add.s32 	%r215, %r212, %r214;
	shr.s32 	%r216, %r215, 7;
$L__tmp2:
	.loc	2 44 22
	add.s32 	%r217, %r144, 255;
	.loc	2 44 28
	shr.s32 	%r218, %r217, 31;
	shr.u32 	%r219, %r218, 24;
	add.s32 	%r220, %r217, %r219;
	shr.s32 	%r221, %r220, 8;
$L__tmp3:
	.loc	1 60 38
	shl.b32 	%r223, %r221, 3;
	ld.param.u32 	%r224, [matmul_kernel_bias_param_7];
	ld.param.u32 	%r225, [matmul_kernel_bias_param_8];
	.loc	1 61 22
	div.s32 	%r226, %r147, %r223;
	.loc	1 62 29
	shl.b32 	%r227, %r226, 3;
	.loc	1 63 35
	sub.s32 	%r228, %r216, %r227;
	.loc	1 63 48
	min.s32 	%r229, %r228, 8;
	.loc	1 64 33
	rem.s32 	%r230, %r147, %r229;
	.loc	1 64 27
	add.s32 	%r231, %r227, %r230;
	mul.lo.s32 	%r232, %r226, %r223;
	sub.s32 	%r233, %r147, %r232;
	.loc	1 65 40
	div.s32 	%r234, %r233, %r229;
	.loc	1 74 23
	shl.b32 	%r1, %r231, 7;
	.loc	1 74 51
	mov.u32 	%r2, %tid.x;
	and.b32  	%r3, %r2, 31;
	bfe.u32 	%r235, %r2, 2, 6;
	or.b32  	%r236, %r235, 64;
	bfe.u32 	%r4, %r2, 5, 3;
	or.b32  	%r5, %r4, 8;
	or.b32  	%r6, %r4, 16;
	or.b32  	%r7, %r4, 24;
	.loc	1 74 38
	or.b32  	%r237, %r1, %r235;
	or.b32  	%r238, %r1, %r236;
	.loc	1 74 68
	rem.s32 	%r239, %r237, %r143;
	rem.s32 	%r240, %r238, %r143;
	.loc	1 75 23
	shl.b32 	%r8, %r234, 8;
	.loc	1 75 51
	shl.b32 	%r241, %r2, 3;
	and.b32  	%r9, %r241, 24;
	and.b32  	%r242, %r241, 248;
	.loc	1 75 38
	or.b32  	%r10, %r8, %r242;
	.loc	1 75 68
	rem.s32 	%r243, %r10, %r144;
	.loc	1 77 53
	mad.lo.s32 	%r244, %r239, %r224, %r9;
	mad.lo.s32 	%r245, %r240, %r224, %r9;
	.loc	1 77 22
	mul.wide.s32 	%rd38, %r244, 2;
	add.s64 	%rd26, %rd22, %rd38;
	mul.wide.s32 	%rd39, %r245, 2;
	add.s64 	%rd27, %rd22, %rd39;
	.loc	1 78 40
	shl.b32 	%r246, %r225, 3;
	.loc	1 78 52
	mad.lo.s32 	%r247, %r4, %r225, %r243;
	add.s32 	%r248, %r247, %r246;
	add.s32 	%r249, %r248, %r246;
	add.s32 	%r250, %r249, %r246;
	.loc	1 78 22
	mul.wide.s32 	%rd40, %r247, 2;
	add.s64 	%rd28, %rd23, %rd40;
	mul.wide.s32 	%rd41, %r248, 2;
	add.s64 	%rd29, %rd23, %rd41;
	mul.wide.s32 	%rd42, %r249, 2;
	add.s64 	%rd30, %rd23, %rd42;
	mul.wide.s32 	%rd43, %r250, 2;
	add.s64 	%rd31, %rd23, %rd43;
$L__tmp4:
	.loc	2 44 22
	add.s32 	%r251, %r145, 31;
$L__tmp5:
	.loc	1 103 33
	shl.b32 	%r255, %r225, 5;
	.loc	1 93 22
	setp.lt.s32 	%p13, %r251, 32;
	setp.gt.s32 	%p14, %r251, 31;
	.loc	1 96 72
	setp.lt.s32 	%p15, %r9, %r145;
	.loc	1 96 20
	shl.b32 	%r256, %r235, 5;
	xor.b32  	%r257, %r241, %r2;
	and.b32  	%r258, %r257, 24;
	or.b32  	%r12, %r256, %r258;
	shl.b32 	%r259, %r12, 1;
	mov.u32 	%r260, global_smem;
	add.s32 	%r148, %r260, %r259;
	shl.b32 	%r261, %r236, 5;
	or.b32  	%r13, %r261, %r258;
	shl.b32 	%r262, %r13, 1;
	add.s32 	%r150, %r260, %r262;
	selp.b32 	%r263, 16, 0, %p14;
	selp.b32 	%r151, %r263, 0, %p15;
	mov.pred 	%p1, -1;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r148 + 0 ], [ %rd26 + 0 ], 0x10, %r151;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r150 + 0 ], [ %rd27 + 0 ], 0x10, %r151;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 72
	setp.lt.s32 	%p16, %r4, %r145;
	setp.lt.s32 	%p17, %r5, %r145;
	setp.lt.s32 	%p18, %r6, %r145;
	setp.lt.s32 	%p19, %r7, %r145;
	.loc	1 97 20
	shl.b32 	%r264, %r4, 8;
	shl.b32 	%r265, %r4, 3;
	xor.b32  	%r266, %r265, %r242;
	or.b32  	%r14, %r266, %r264;
	shl.b32 	%r267, %r14, 1;
	add.s32 	%r268, %r260, 16384;
	add.s32 	%r152, %r268, %r267;
	shl.b32 	%r269, %r5, 8;
	or.b32  	%r15, %r269, %r266;
	shl.b32 	%r270, %r15, 1;
	add.s32 	%r154, %r268, %r270;
	shl.b32 	%r271, %r6, 8;
	or.b32  	%r16, %r271, %r266;
	shl.b32 	%r272, %r16, 1;
	add.s32 	%r156, %r268, %r272;
	shl.b32 	%r273, %r7, 8;
	or.b32  	%r17, %r273, %r266;
	shl.b32 	%r274, %r17, 1;
	add.s32 	%r158, %r268, %r274;
	selp.b32 	%r153, %r263, 0, %p16;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r152 + 0 ], [ %rd28 + 0 ], 0x10, %r153;
	// end inline asm
	selp.b32 	%r155, %r263, 0, %p17;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r154 + 0 ], [ %rd29 + 0 ], 0x10, %r155;
	// end inline asm
	selp.b32 	%r157, %r263, 0, %p18;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r156 + 0 ], [ %rd30 + 0 ], 0x10, %r157;
	// end inline asm
	selp.b32 	%r159, %r263, 0, %p19;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r158 + 0 ], [ %rd31 + 0 ], 0x10, %r159;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	setp.gt.s32 	%p20, %r251, 63;
	.loc	1 102 18
	add.s64 	%rd32, %rd26, 64;
	add.s64 	%rd33, %rd27, 64;
	.loc	1 103 18
	mul.wide.s32 	%rd44, %r255, 2;
	add.s64 	%rd34, %rd28, %rd44;
	add.s64 	%rd35, %rd29, %rd44;
	add.s64 	%rd36, %rd30, %rd44;
	add.s64 	%rd37, %rd31, %rd44;
	.loc	1 96 53
	or.b32  	%r275, %r9, 32;
	.loc	1 96 72
	setp.lt.s32 	%p21, %r275, %r145;
	.loc	1 96 20
	bar.sync 	0;
	add.s32 	%r276, %r260, 8192;
	add.s32 	%r160, %r276, %r259;
	add.s32 	%r162, %r276, %r262;
	selp.b32 	%r277, 16, 0, %p20;
	selp.b32 	%r163, %r277, 0, %p21;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r160 + 0 ], [ %rd32 + 0 ], 0x10, %r163;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r162 + 0 ], [ %rd33 + 0 ], 0x10, %r163;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 53
	or.b32  	%r18, %r4, 32;
	or.b32  	%r19, %r4, 40;
	or.b32  	%r20, %r4, 48;
	or.b32  	%r21, %r4, 56;
	.loc	1 97 72
	setp.lt.s32 	%p22, %r18, %r145;
	setp.lt.s32 	%p23, %r19, %r145;
	setp.lt.s32 	%p24, %r20, %r145;
	setp.lt.s32 	%p25, %r21, %r145;
	.loc	1 97 20
	add.s32 	%r278, %r260, 32768;
	add.s32 	%r164, %r278, %r267;
	add.s32 	%r166, %r278, %r270;
	add.s32 	%r168, %r278, %r272;
	add.s32 	%r170, %r278, %r274;
	selp.b32 	%r165, %r277, 0, %p22;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r164 + 0 ], [ %rd34 + 0 ], 0x10, %r165;
	// end inline asm
	selp.b32 	%r167, %r277, 0, %p23;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r166 + 0 ], [ %rd35 + 0 ], 0x10, %r167;
	// end inline asm
	selp.b32 	%r169, %r277, 0, %p24;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r168 + 0 ], [ %rd36 + 0 ], 0x10, %r169;
	// end inline asm
	selp.b32 	%r171, %r277, 0, %p25;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r170 + 0 ], [ %rd37 + 0 ], 0x10, %r171;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 96 20
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	and.b32  	%r279, %r2, 7;
	bfe.u32 	%r22, %r2, 4, 1;
	bfe.u32 	%r23, %r2, 1, 2;
	shr.u32 	%r280, %r2, 3;
	and.b32  	%r24, %r280, 16;
	and.b32  	%r281, %r2, 15;
	or.b32  	%r282, %r281, %r24;
	xor.b32  	%r283, %r22, %r23;
	shl.b32 	%r25, %r282, 5;
	shl.b32 	%r284, %r283, 3;
	or.b32  	%r26, %r25, %r284;
	shl.b32 	%r285, %r26, 1;
	add.s32 	%r176, %r260, %r285;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1438, %r1439, %r1440, %r1441 }, [ %r176 + 0 ];
	// end inline asm
	add.s32 	%r181, %r176, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1434, %r1435, %r1436, %r1437 }, [ %r181 + 0 ];
	// end inline asm
	add.s32 	%r186, %r176, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1430, %r1431, %r1432, %r1433 }, [ %r186 + 0 ];
	// end inline asm
	add.s32 	%r191, %r176, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1426, %r1427, %r1428, %r1429 }, [ %r191 + 0 ];
	// end inline asm
	.loc	1 97 20
	bfe.u32 	%r43, %r2, 5, 2;
	shl.b32 	%r286, %r22, 2;
	or.b32  	%r287, %r286, %r43;
	xor.b32  	%r288, %r287, %r279;
	shl.b32 	%r289, %r281, 8;
	shl.b32 	%r290, %r288, 3;
	or.b32  	%r44, %r290, %r289;
	shl.b32 	%r291, %r44, 1;
	add.s32 	%r196, %r268, %r291;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1422, %r1423, %r1424, %r1425 }, [ %r196 + 0 ];
	// end inline asm
	or.b32  	%r292, %r287, 8;
	xor.b32  	%r293, %r292, %r279;
	shl.b32 	%r294, %r293, 3;
	add.s32 	%r49, %r294, %r289;
	shl.b32 	%r295, %r49, 1;
	add.s32 	%r201, %r268, %r295;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1418, %r1419, %r1420, %r1421 }, [ %r201 + 0 ];
	// end inline asm
	or.b32  	%r296, %r287, 16;
	xor.b32  	%r297, %r296, %r279;
	shl.b32 	%r298, %r297, 3;
	add.s32 	%r54, %r298, %r289;
	shl.b32 	%r299, %r54, 1;
	add.s32 	%r206, %r268, %r299;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1414, %r1415, %r1416, %r1417 }, [ %r206 + 0 ];
	// end inline asm
	or.b32  	%r300, %r287, 24;
	xor.b32  	%r301, %r300, %r279;
	shl.b32 	%r302, %r301, 3;
	add.s32 	%r59, %r302, %r289;
	shl.b32 	%r303, %r59, 1;
	add.s32 	%r211, %r268, %r303;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1410, %r1411, %r1412, %r1413 }, [ %r211 + 0 ];
	// end inline asm
	mov.b16 	%rs661, 0x0000;
	mov.u16 	%rs662, %rs661;
	mov.u16 	%rs663, %rs661;
	mov.u16 	%rs664, %rs661;
	mov.u16 	%rs665, %rs661;
	mov.u16 	%rs666, %rs661;
	mov.u16 	%rs667, %rs661;
	mov.u16 	%rs668, %rs661;
	mov.u16 	%rs669, %rs661;
	mov.u16 	%rs670, %rs661;
	mov.u16 	%rs671, %rs661;
	mov.u16 	%rs672, %rs661;
	mov.u16 	%rs673, %rs661;
	mov.u16 	%rs674, %rs661;
	mov.u16 	%rs675, %rs661;
	mov.u16 	%rs676, %rs661;
	mov.u16 	%rs677, %rs661;
	mov.u16 	%rs678, %rs661;
	mov.u16 	%rs679, %rs661;
	mov.u16 	%rs680, %rs661;
	mov.u16 	%rs681, %rs661;
	mov.u16 	%rs682, %rs661;
	mov.u16 	%rs683, %rs661;
	mov.u16 	%rs684, %rs661;
	mov.u16 	%rs685, %rs661;
	mov.u16 	%rs686, %rs661;
	mov.u16 	%rs687, %rs661;
	mov.u16 	%rs688, %rs661;
	mov.u16 	%rs689, %rs661;
	mov.u16 	%rs690, %rs661;
	mov.u16 	%rs691, %rs661;
	mov.u16 	%rs692, %rs661;
	mov.u16 	%rs693, %rs661;
	mov.u16 	%rs694, %rs661;
	mov.u16 	%rs695, %rs661;
	mov.u16 	%rs696, %rs661;
	mov.u16 	%rs697, %rs661;
	mov.u16 	%rs698, %rs661;
	mov.u16 	%rs699, %rs661;
	mov.u16 	%rs700, %rs661;
	mov.u16 	%rs701, %rs661;
	mov.u16 	%rs702, %rs661;
	mov.u16 	%rs703, %rs661;
	mov.u16 	%rs704, %rs661;
	mov.u16 	%rs705, %rs661;
	mov.u16 	%rs706, %rs661;
	mov.u16 	%rs707, %rs661;
	mov.u16 	%rs708, %rs661;
	mov.u16 	%rs709, %rs661;
	mov.u16 	%rs710, %rs661;
	mov.u16 	%rs711, %rs661;
	mov.u16 	%rs712, %rs661;
	mov.u16 	%rs713, %rs661;
	mov.u16 	%rs714, %rs661;
	mov.u16 	%rs715, %rs661;
	mov.u16 	%rs716, %rs661;
	mov.u16 	%rs717, %rs661;
	mov.u16 	%rs718, %rs661;
	mov.u16 	%rs719, %rs661;
	mov.u16 	%rs720, %rs661;
	mov.u16 	%rs721, %rs661;
	mov.u16 	%rs722, %rs661;
	mov.u16 	%rs723, %rs661;
	mov.u16 	%rs724, %rs661;
	mov.u16 	%rs725, %rs661;
	mov.u16 	%rs726, %rs661;
	mov.u16 	%rs727, %rs661;
	mov.u16 	%rs728, %rs661;
	mov.u16 	%rs729, %rs661;
	mov.u16 	%rs730, %rs661;
	mov.u16 	%rs731, %rs661;
	mov.u16 	%rs732, %rs661;
	mov.u16 	%rs733, %rs661;
	mov.u16 	%rs734, %rs661;
	mov.u16 	%rs735, %rs661;
	mov.u16 	%rs736, %rs661;
	mov.u16 	%rs737, %rs661;
	mov.u16 	%rs738, %rs661;
	mov.u16 	%rs739, %rs661;
	mov.u16 	%rs740, %rs661;
	mov.u16 	%rs741, %rs661;
	mov.u16 	%rs742, %rs661;
	mov.u16 	%rs743, %rs661;
	mov.u16 	%rs744, %rs661;
	mov.u16 	%rs745, %rs661;
	mov.u16 	%rs746, %rs661;
	mov.u16 	%rs747, %rs661;
	mov.u16 	%rs748, %rs661;
	mov.u16 	%rs749, %rs661;
	mov.u16 	%rs750, %rs661;
	mov.u16 	%rs751, %rs661;
	mov.u16 	%rs752, %rs661;
	mov.u16 	%rs753, %rs661;
	mov.u16 	%rs754, %rs661;
	mov.u16 	%rs755, %rs661;
	mov.u16 	%rs756, %rs661;
	mov.u16 	%rs757, %rs661;
	mov.u16 	%rs758, %rs661;
	mov.u16 	%rs759, %rs661;
	mov.u16 	%rs760, %rs661;
	mov.u16 	%rs761, %rs661;
	mov.u16 	%rs762, %rs661;
	mov.u16 	%rs763, %rs661;
	mov.u16 	%rs764, %rs661;
	mov.u16 	%rs765, %rs661;
	mov.u16 	%rs766, %rs661;
	mov.u16 	%rs767, %rs661;
	mov.u16 	%rs768, %rs661;
	mov.u16 	%rs769, %rs661;
	mov.u16 	%rs770, %rs661;
	mov.u16 	%rs771, %rs661;
	mov.u16 	%rs772, %rs661;
	mov.u16 	%rs773, %rs661;
	mov.u16 	%rs774, %rs661;
	mov.u16 	%rs775, %rs661;
	mov.u16 	%rs776, %rs661;
	mov.u16 	%rs777, %rs661;
	mov.u16 	%rs778, %rs661;
	mov.u16 	%rs779, %rs661;
	mov.u16 	%rs780, %rs661;
	mov.u16 	%rs781, %rs661;
	mov.u16 	%rs782, %rs661;
	mov.u16 	%rs783, %rs661;
	mov.u16 	%rs784, %rs661;
	mov.u16 	%rs785, %rs661;
	mov.u16 	%rs786, %rs661;
	mov.u16 	%rs787, %rs661;
	mov.u16 	%rs788, %rs661;
	.loc	1 93 22
	@%p13 bra 	$L__BB0_3;
	.loc	1 0 22
	cvt.s64.s32 	%rd1, %r244;
	cvt.s64.s32 	%rd2, %r245;
	cvt.s64.s32 	%rd3, %r247;
	cvt.s64.s32 	%rd4, %r248;
	cvt.s64.s32 	%rd5, %r249;
	cvt.s64.s32 	%rd6, %r250;
	shr.s32 	%r252, %r251, 31;
	shr.u32 	%r253, %r252, 27;
	add.s32 	%r254, %r251, %r253;
	shr.s32 	%r11, %r254, 5;
	cvt.s64.s32 	%rd7, %r255;
	add.s32 	%r64, %r11, -2;
	or.b32  	%r308, %r22, 2;
	xor.b32  	%r309, %r308, %r23;
	shl.b32 	%r310, %r309, 3;
	or.b32  	%r65, %r25, %r310;
	.loc	1 93 22
	shl.b64 	%rd8, %rd6, 1;
	shl.b64 	%rd45, %rd7, 2;
	add.s64 	%rd109, %rd23, %rd45;
	shl.b64 	%rd10, %rd7, 1;
	shl.b64 	%rd11, %rd5, 1;
	shl.b64 	%rd12, %rd4, 1;
	shl.b64 	%rd13, %rd3, 1;
	shl.b64 	%rd46, %rd2, 1;
	add.s64 	%rd47, %rd46, %rd22;
	add.s64 	%rd108, %rd47, 128;
	shl.b64 	%rd48, %rd1, 1;
	add.s64 	%rd49, %rd48, %rd22;
	add.s64 	%rd107, %rd49, 128;
	or.b32  	%r66, %r9, 64;
	mov.b16 	%rs661, 0x0000;
	mov.b32 	%r1445, 1;
	mov.b32 	%r1409, 0;
	shl.b32 	%r1043, %r65, 1;
	mov.u32 	%r1442, %r268;
	mov.u32 	%r1443, %r260;
	mov.u32 	%r1444, %r1409;
	mov.u16 	%rs662, %rs661;
	mov.u16 	%rs663, %rs661;
	mov.u16 	%rs664, %rs661;
	mov.u16 	%rs665, %rs661;
	mov.u16 	%rs666, %rs661;
	mov.u16 	%rs667, %rs661;
	mov.u16 	%rs668, %rs661;
	mov.u16 	%rs669, %rs661;
	mov.u16 	%rs670, %rs661;
	mov.u16 	%rs671, %rs661;
	mov.u16 	%rs672, %rs661;
	mov.u16 	%rs673, %rs661;
	mov.u16 	%rs674, %rs661;
	mov.u16 	%rs675, %rs661;
	mov.u16 	%rs676, %rs661;
	mov.u16 	%rs677, %rs661;
	mov.u16 	%rs678, %rs661;
	mov.u16 	%rs679, %rs661;
	mov.u16 	%rs680, %rs661;
	mov.u16 	%rs681, %rs661;
	mov.u16 	%rs682, %rs661;
	mov.u16 	%rs683, %rs661;
	mov.u16 	%rs684, %rs661;
	mov.u16 	%rs685, %rs661;
	mov.u16 	%rs686, %rs661;
	mov.u16 	%rs687, %rs661;
	mov.u16 	%rs688, %rs661;
	mov.u16 	%rs689, %rs661;
	mov.u16 	%rs690, %rs661;
	mov.u16 	%rs691, %rs661;
	mov.u16 	%rs692, %rs661;
	mov.u16 	%rs693, %rs661;
	mov.u16 	%rs694, %rs661;
	mov.u16 	%rs695, %rs661;
	mov.u16 	%rs696, %rs661;
	mov.u16 	%rs697, %rs661;
	mov.u16 	%rs698, %rs661;
	mov.u16 	%rs699, %rs661;
	mov.u16 	%rs700, %rs661;
	mov.u16 	%rs701, %rs661;
	mov.u16 	%rs702, %rs661;
	mov.u16 	%rs703, %rs661;
	mov.u16 	%rs704, %rs661;
	mov.u16 	%rs705, %rs661;
	mov.u16 	%rs706, %rs661;
	mov.u16 	%rs707, %rs661;
	mov.u16 	%rs708, %rs661;
	mov.u16 	%rs709, %rs661;
	mov.u16 	%rs710, %rs661;
	mov.u16 	%rs711, %rs661;
	mov.u16 	%rs712, %rs661;
	mov.u16 	%rs713, %rs661;
	mov.u16 	%rs714, %rs661;
	mov.u16 	%rs715, %rs661;
	mov.u16 	%rs716, %rs661;
	mov.u16 	%rs717, %rs661;
	mov.u16 	%rs718, %rs661;
	mov.u16 	%rs719, %rs661;
	mov.u16 	%rs720, %rs661;
	mov.u16 	%rs721, %rs661;
	mov.u16 	%rs722, %rs661;
	mov.u16 	%rs723, %rs661;
	mov.u16 	%rs724, %rs661;
	mov.u16 	%rs725, %rs661;
	mov.u16 	%rs726, %rs661;
	mov.u16 	%rs727, %rs661;
	mov.u16 	%rs728, %rs661;
	mov.u16 	%rs729, %rs661;
	mov.u16 	%rs730, %rs661;
	mov.u16 	%rs731, %rs661;
	mov.u16 	%rs732, %rs661;
	mov.u16 	%rs733, %rs661;
	mov.u16 	%rs734, %rs661;
	mov.u16 	%rs735, %rs661;
	mov.u16 	%rs736, %rs661;
	mov.u16 	%rs737, %rs661;
	mov.u16 	%rs738, %rs661;
	mov.u16 	%rs739, %rs661;
	mov.u16 	%rs740, %rs661;
	mov.u16 	%rs741, %rs661;
	mov.u16 	%rs742, %rs661;
	mov.u16 	%rs743, %rs661;
	mov.u16 	%rs744, %rs661;
	mov.u16 	%rs745, %rs661;
	mov.u16 	%rs746, %rs661;
	mov.u16 	%rs747, %rs661;
	mov.u16 	%rs748, %rs661;
	mov.u16 	%rs749, %rs661;
	mov.u16 	%rs750, %rs661;
	mov.u16 	%rs751, %rs661;
	mov.u16 	%rs752, %rs661;
	mov.u16 	%rs753, %rs661;
	mov.u16 	%rs754, %rs661;
	mov.u16 	%rs755, %rs661;
	mov.u16 	%rs756, %rs661;
	mov.u16 	%rs757, %rs661;
	mov.u16 	%rs758, %rs661;
	mov.u16 	%rs759, %rs661;
	mov.u16 	%rs760, %rs661;
	mov.u16 	%rs761, %rs661;
	mov.u16 	%rs762, %rs661;
	mov.u16 	%rs763, %rs661;
	mov.u16 	%rs764, %rs661;
	mov.u16 	%rs765, %rs661;
	mov.u16 	%rs766, %rs661;
	mov.u16 	%rs767, %rs661;
	mov.u16 	%rs768, %rs661;
	mov.u16 	%rs769, %rs661;
	mov.u16 	%rs770, %rs661;
	mov.u16 	%rs771, %rs661;
	mov.u16 	%rs772, %rs661;
	mov.u16 	%rs773, %rs661;
	mov.u16 	%rs774, %rs661;
	mov.u16 	%rs775, %rs661;
	mov.u16 	%rs776, %rs661;
	mov.u16 	%rs777, %rs661;
	mov.u16 	%rs778, %rs661;
	mov.u16 	%rs779, %rs661;
	mov.u16 	%rs780, %rs661;
	mov.u16 	%rs781, %rs661;
	mov.u16 	%rs782, %rs661;
	mov.u16 	%rs783, %rs661;
	mov.u16 	%rs784, %rs661;
	mov.u16 	%rs785, %rs661;
	mov.u16 	%rs786, %rs661;
	mov.u16 	%rs787, %rs661;
	mov.u16 	%rs788, %rs661;
	mov.u32 	%r1446, %r1409;
$L__BB0_2:
	setp.lt.s32 	%p32, %r1446, %r64;
	.loc	1 96 20
	add.s32 	%r315, %r1443, %r1043;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r675, %r676, %r677, %r678 }, [ %r315 + 0 ];
	// end inline asm
	add.s32 	%r320, %r315, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r755, %r756, %r757, %r758 }, [ %r320 + 0 ];
	// end inline asm
	add.s32 	%r325, %r315, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r835, %r836, %r837, %r838 }, [ %r325 + 0 ];
	// end inline asm
	add.s32 	%r330, %r315, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r915, %r916, %r917, %r918 }, [ %r330 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r1045, %r1442, %r291;
	add.s32 	%r335, %r1045, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r679, %r680, %r689, %r690 }, [ %r335 + 0 ];
	// end inline asm
	add.s32 	%r1047, %r1442, %r295;
	add.s32 	%r340, %r1047, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r699, %r700, %r709, %r710 }, [ %r340 + 0 ];
	// end inline asm
	add.s32 	%r1049, %r1442, %r299;
	add.s32 	%r345, %r1049, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r719, %r720, %r729, %r730 }, [ %r345 + 0 ];
	// end inline asm
	add.s32 	%r1051, %r1442, %r303;
	add.s32 	%r350, %r1051, 8192;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r739, %r740, %r749, %r750 }, [ %r350 + 0 ];
	// end inline asm
	.loc	1 100 35
	mov.b32 	%r671, {%rs661, %rs662};
	mov.b32 	%r672, {%rs663, %rs664};
	mov.b32 	%r681, {%rs665, %rs666};
	mov.b32 	%r682, {%rs667, %rs668};
	mov.b32 	%r691, {%rs669, %rs670};
	mov.b32 	%r692, {%rs671, %rs672};
	mov.b32 	%r701, {%rs673, %rs674};
	mov.b32 	%r702, {%rs675, %rs676};
	mov.b32 	%r711, {%rs677, %rs678};
	mov.b32 	%r712, {%rs679, %rs680};
	mov.b32 	%r721, {%rs681, %rs682};
	mov.b32 	%r722, {%rs683, %rs684};
	mov.b32 	%r731, {%rs685, %rs686};
	mov.b32 	%r732, {%rs687, %rs688};
	mov.b32 	%r741, {%rs689, %rs690};
	mov.b32 	%r742, {%rs691, %rs692};
	mov.b32 	%r751, {%rs693, %rs694};
	mov.b32 	%r752, {%rs695, %rs696};
	mov.b32 	%r761, {%rs697, %rs698};
	mov.b32 	%r762, {%rs699, %rs700};
	mov.b32 	%r771, {%rs701, %rs702};
	mov.b32 	%r772, {%rs703, %rs704};
	mov.b32 	%r781, {%rs705, %rs706};
	mov.b32 	%r782, {%rs707, %rs708};
	mov.b32 	%r791, {%rs709, %rs710};
	mov.b32 	%r792, {%rs711, %rs712};
	mov.b32 	%r801, {%rs713, %rs714};
	mov.b32 	%r802, {%rs715, %rs716};
	mov.b32 	%r811, {%rs717, %rs718};
	mov.b32 	%r812, {%rs719, %rs720};
	mov.b32 	%r821, {%rs721, %rs722};
	mov.b32 	%r822, {%rs723, %rs724};
	mov.b32 	%r831, {%rs725, %rs726};
	mov.b32 	%r832, {%rs727, %rs728};
	mov.b32 	%r841, {%rs729, %rs730};
	mov.b32 	%r842, {%rs731, %rs732};
	mov.b32 	%r851, {%rs733, %rs734};
	mov.b32 	%r852, {%rs735, %rs736};
	mov.b32 	%r861, {%rs737, %rs738};
	mov.b32 	%r862, {%rs739, %rs740};
	mov.b32 	%r871, {%rs741, %rs742};
	mov.b32 	%r872, {%rs743, %rs744};
	mov.b32 	%r881, {%rs745, %rs746};
	mov.b32 	%r882, {%rs747, %rs748};
	mov.b32 	%r891, {%rs749, %rs750};
	mov.b32 	%r892, {%rs751, %rs752};
	mov.b32 	%r901, {%rs753, %rs754};
	mov.b32 	%r902, {%rs755, %rs756};
	mov.b32 	%r911, {%rs757, %rs758};
	mov.b32 	%r912, {%rs759, %rs760};
	mov.b32 	%r921, {%rs761, %rs762};
	mov.b32 	%r922, {%rs763, %rs764};
	mov.b32 	%r931, {%rs765, %rs766};
	mov.b32 	%r932, {%rs767, %rs768};
	mov.b32 	%r941, {%rs769, %rs770};
	mov.b32 	%r942, {%rs771, %rs772};
	mov.b32 	%r951, {%rs773, %rs774};
	mov.b32 	%r952, {%rs775, %rs776};
	mov.b32 	%r961, {%rs777, %rs778};
	mov.b32 	%r962, {%rs779, %rs780};
	mov.b32 	%r971, {%rs781, %rs782};
	mov.b32 	%r972, {%rs783, %rs784};
	mov.b32 	%r981, {%rs785, %rs786};
	mov.b32 	%r982, {%rs787, %rs788};
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r671, %r672 }, { %r1438, %r1439, %r1440, %r1441 }, { %r1422, %r1423 }, { %r671, %r672 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r681, %r682 }, { %r1438, %r1439, %r1440, %r1441 }, { %r1424, %r1425 }, { %r681, %r682 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r691, %r692 }, { %r1438, %r1439, %r1440, %r1441 }, { %r1418, %r1419 }, { %r691, %r692 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r701, %r702 }, { %r1438, %r1439, %r1440, %r1441 }, { %r1420, %r1421 }, { %r701, %r702 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r711, %r712 }, { %r1438, %r1439, %r1440, %r1441 }, { %r1414, %r1415 }, { %r711, %r712 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r721, %r722 }, { %r1438, %r1439, %r1440, %r1441 }, { %r1416, %r1417 }, { %r721, %r722 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r731, %r732 }, { %r1438, %r1439, %r1440, %r1441 }, { %r1410, %r1411 }, { %r731, %r732 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r741, %r742 }, { %r1438, %r1439, %r1440, %r1441 }, { %r1412, %r1413 }, { %r741, %r742 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r751, %r752 }, { %r1434, %r1435, %r1436, %r1437 }, { %r1422, %r1423 }, { %r751, %r752 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r761, %r762 }, { %r1434, %r1435, %r1436, %r1437 }, { %r1424, %r1425 }, { %r761, %r762 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r771, %r772 }, { %r1434, %r1435, %r1436, %r1437 }, { %r1418, %r1419 }, { %r771, %r772 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r781, %r782 }, { %r1434, %r1435, %r1436, %r1437 }, { %r1420, %r1421 }, { %r781, %r782 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r791, %r792 }, { %r1434, %r1435, %r1436, %r1437 }, { %r1414, %r1415 }, { %r791, %r792 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r801, %r802 }, { %r1434, %r1435, %r1436, %r1437 }, { %r1416, %r1417 }, { %r801, %r802 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r811, %r812 }, { %r1434, %r1435, %r1436, %r1437 }, { %r1410, %r1411 }, { %r811, %r812 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r821, %r822 }, { %r1434, %r1435, %r1436, %r1437 }, { %r1412, %r1413 }, { %r821, %r822 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r831, %r832 }, { %r1430, %r1431, %r1432, %r1433 }, { %r1422, %r1423 }, { %r831, %r832 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r841, %r842 }, { %r1430, %r1431, %r1432, %r1433 }, { %r1424, %r1425 }, { %r841, %r842 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r851, %r852 }, { %r1430, %r1431, %r1432, %r1433 }, { %r1418, %r1419 }, { %r851, %r852 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r861, %r862 }, { %r1430, %r1431, %r1432, %r1433 }, { %r1420, %r1421 }, { %r861, %r862 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r871, %r872 }, { %r1430, %r1431, %r1432, %r1433 }, { %r1414, %r1415 }, { %r871, %r872 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r881, %r882 }, { %r1430, %r1431, %r1432, %r1433 }, { %r1416, %r1417 }, { %r881, %r882 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r891, %r892 }, { %r1430, %r1431, %r1432, %r1433 }, { %r1410, %r1411 }, { %r891, %r892 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r901, %r902 }, { %r1430, %r1431, %r1432, %r1433 }, { %r1412, %r1413 }, { %r901, %r902 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r911, %r912 }, { %r1426, %r1427, %r1428, %r1429 }, { %r1422, %r1423 }, { %r911, %r912 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r921, %r922 }, { %r1426, %r1427, %r1428, %r1429 }, { %r1424, %r1425 }, { %r921, %r922 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r931, %r932 }, { %r1426, %r1427, %r1428, %r1429 }, { %r1418, %r1419 }, { %r931, %r932 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r941, %r942 }, { %r1426, %r1427, %r1428, %r1429 }, { %r1420, %r1421 }, { %r941, %r942 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r951, %r952 }, { %r1426, %r1427, %r1428, %r1429 }, { %r1414, %r1415 }, { %r951, %r952 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r961, %r962 }, { %r1426, %r1427, %r1428, %r1429 }, { %r1416, %r1417 }, { %r961, %r962 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r971, %r972 }, { %r1426, %r1427, %r1428, %r1429 }, { %r1410, %r1411 }, { %r971, %r972 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r981, %r982 }, { %r1426, %r1427, %r1428, %r1429 }, { %r1412, %r1413 }, { %r981, %r982 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r671, %r672 }, { %r675, %r676, %r677, %r678 }, { %r679, %r680 }, { %r671, %r672 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r681, %r682 }, { %r675, %r676, %r677, %r678 }, { %r689, %r690 }, { %r681, %r682 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r691, %r692 }, { %r675, %r676, %r677, %r678 }, { %r699, %r700 }, { %r691, %r692 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r701, %r702 }, { %r675, %r676, %r677, %r678 }, { %r709, %r710 }, { %r701, %r702 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r711, %r712 }, { %r675, %r676, %r677, %r678 }, { %r719, %r720 }, { %r711, %r712 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r721, %r722 }, { %r675, %r676, %r677, %r678 }, { %r729, %r730 }, { %r721, %r722 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r731, %r732 }, { %r675, %r676, %r677, %r678 }, { %r739, %r740 }, { %r731, %r732 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r741, %r742 }, { %r675, %r676, %r677, %r678 }, { %r749, %r750 }, { %r741, %r742 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r751, %r752 }, { %r755, %r756, %r757, %r758 }, { %r679, %r680 }, { %r751, %r752 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r761, %r762 }, { %r755, %r756, %r757, %r758 }, { %r689, %r690 }, { %r761, %r762 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r771, %r772 }, { %r755, %r756, %r757, %r758 }, { %r699, %r700 }, { %r771, %r772 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r781, %r782 }, { %r755, %r756, %r757, %r758 }, { %r709, %r710 }, { %r781, %r782 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r791, %r792 }, { %r755, %r756, %r757, %r758 }, { %r719, %r720 }, { %r791, %r792 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r801, %r802 }, { %r755, %r756, %r757, %r758 }, { %r729, %r730 }, { %r801, %r802 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r811, %r812 }, { %r755, %r756, %r757, %r758 }, { %r739, %r740 }, { %r811, %r812 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r821, %r822 }, { %r755, %r756, %r757, %r758 }, { %r749, %r750 }, { %r821, %r822 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r831, %r832 }, { %r835, %r836, %r837, %r838 }, { %r679, %r680 }, { %r831, %r832 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r841, %r842 }, { %r835, %r836, %r837, %r838 }, { %r689, %r690 }, { %r841, %r842 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r851, %r852 }, { %r835, %r836, %r837, %r838 }, { %r699, %r700 }, { %r851, %r852 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r861, %r862 }, { %r835, %r836, %r837, %r838 }, { %r709, %r710 }, { %r861, %r862 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r871, %r872 }, { %r835, %r836, %r837, %r838 }, { %r719, %r720 }, { %r871, %r872 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r881, %r882 }, { %r835, %r836, %r837, %r838 }, { %r729, %r730 }, { %r881, %r882 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r891, %r892 }, { %r835, %r836, %r837, %r838 }, { %r739, %r740 }, { %r891, %r892 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r901, %r902 }, { %r835, %r836, %r837, %r838 }, { %r749, %r750 }, { %r901, %r902 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r911, %r912 }, { %r915, %r916, %r917, %r918 }, { %r679, %r680 }, { %r911, %r912 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r921, %r922 }, { %r915, %r916, %r917, %r918 }, { %r689, %r690 }, { %r921, %r922 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r931, %r932 }, { %r915, %r916, %r917, %r918 }, { %r699, %r700 }, { %r931, %r932 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r941, %r942 }, { %r915, %r916, %r917, %r918 }, { %r709, %r710 }, { %r941, %r942 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r951, %r952 }, { %r915, %r916, %r917, %r918 }, { %r719, %r720 }, { %r951, %r952 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r961, %r962 }, { %r915, %r916, %r917, %r918 }, { %r729, %r730 }, { %r961, %r962 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r971, %r972 }, { %r915, %r916, %r917, %r918 }, { %r739, %r740 }, { %r971, %r972 };
	// end inline asm
	// begin inline asm
	mma.sync.aligned.m16n8k16.row.col.f16.f16.f16.f16 { %r981, %r982 }, { %r915, %r916, %r917, %r918 }, { %r749, %r750 }, { %r981, %r982 };
	// end inline asm
	mov.b32 	{%rs661, %rs662}, %r671;
	mov.b32 	{%rs663, %rs664}, %r672;
	mov.b32 	{%rs665, %rs666}, %r681;
	mov.b32 	{%rs667, %rs668}, %r682;
	mov.b32 	{%rs669, %rs670}, %r691;
	mov.b32 	{%rs671, %rs672}, %r692;
	mov.b32 	{%rs673, %rs674}, %r701;
	mov.b32 	{%rs675, %rs676}, %r702;
	mov.b32 	{%rs677, %rs678}, %r711;
	mov.b32 	{%rs679, %rs680}, %r712;
	mov.b32 	{%rs681, %rs682}, %r721;
	mov.b32 	{%rs683, %rs684}, %r722;
	mov.b32 	{%rs685, %rs686}, %r731;
	mov.b32 	{%rs687, %rs688}, %r732;
	mov.b32 	{%rs689, %rs690}, %r741;
	mov.b32 	{%rs691, %rs692}, %r742;
	mov.b32 	{%rs693, %rs694}, %r751;
	mov.b32 	{%rs695, %rs696}, %r752;
	mov.b32 	{%rs697, %rs698}, %r761;
	mov.b32 	{%rs699, %rs700}, %r762;
	mov.b32 	{%rs701, %rs702}, %r771;
	mov.b32 	{%rs703, %rs704}, %r772;
	mov.b32 	{%rs705, %rs706}, %r781;
	mov.b32 	{%rs707, %rs708}, %r782;
	mov.b32 	{%rs709, %rs710}, %r791;
	mov.b32 	{%rs711, %rs712}, %r792;
	mov.b32 	{%rs713, %rs714}, %r801;
	mov.b32 	{%rs715, %rs716}, %r802;
	mov.b32 	{%rs717, %rs718}, %r811;
	mov.b32 	{%rs719, %rs720}, %r812;
	mov.b32 	{%rs721, %rs722}, %r821;
	mov.b32 	{%rs723, %rs724}, %r822;
	mov.b32 	{%rs725, %rs726}, %r831;
	mov.b32 	{%rs727, %rs728}, %r832;
	mov.b32 	{%rs729, %rs730}, %r841;
	mov.b32 	{%rs731, %rs732}, %r842;
	mov.b32 	{%rs733, %rs734}, %r851;
	mov.b32 	{%rs735, %rs736}, %r852;
	mov.b32 	{%rs737, %rs738}, %r861;
	mov.b32 	{%rs739, %rs740}, %r862;
	mov.b32 	{%rs741, %rs742}, %r871;
	mov.b32 	{%rs743, %rs744}, %r872;
	mov.b32 	{%rs745, %rs746}, %r881;
	mov.b32 	{%rs747, %rs748}, %r882;
	mov.b32 	{%rs749, %rs750}, %r891;
	mov.b32 	{%rs751, %rs752}, %r892;
	mov.b32 	{%rs753, %rs754}, %r901;
	mov.b32 	{%rs755, %rs756}, %r902;
	mov.b32 	{%rs757, %rs758}, %r911;
	mov.b32 	{%rs759, %rs760}, %r912;
	mov.b32 	{%rs761, %rs762}, %r921;
	mov.b32 	{%rs763, %rs764}, %r922;
	mov.b32 	{%rs765, %rs766}, %r931;
	mov.b32 	{%rs767, %rs768}, %r932;
	mov.b32 	{%rs769, %rs770}, %r941;
	mov.b32 	{%rs771, %rs772}, %r942;
	mov.b32 	{%rs773, %rs774}, %r951;
	mov.b32 	{%rs775, %rs776}, %r952;
	mov.b32 	{%rs777, %rs778}, %r961;
	mov.b32 	{%rs779, %rs780}, %r962;
	mov.b32 	{%rs781, %rs782}, %r971;
	mov.b32 	{%rs783, %rs784}, %r972;
	mov.b32 	{%rs785, %rs786}, %r981;
	mov.b32 	{%rs787, %rs788}, %r982;
	.loc	1 103 18
	add.s64 	%rd52, %rd109, %rd13;
	add.s64 	%rd53, %rd109, %rd12;
	add.s64 	%rd54, %rd109, %rd11;
	.loc	1 93 22
	add.s64 	%rd55, %rd109, %rd8;
	add.s32 	%r1180, %r1445, 1;
	setp.lt.s32 	%p33, %r1180, 2;
	selp.b32 	%r1445, %r1180, 0, %p33;
	.loc	1 96 72
	add.s32 	%r1181, %r66, %r1409;
	setp.lt.s32 	%p34, %r1181, %r145;
	.loc	1 96 20
	shl.b32 	%r1182, %r1445, 13;
	add.s32 	%r1184, %r260, %r1182;
	bar.sync 	0;
	add.s32 	%r991, %r1184, %r259;
	add.s32 	%r993, %r1184, %r262;
	selp.b32 	%r1187, 16, 0, %p34;
	selp.b32 	%r994, %r1187, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r991 + 0 ], [ %rd107 + 0 ], 0x10, %r994;
	// end inline asm
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r993 + 0 ], [ %rd108 + 0 ], 0x10, %r994;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 97 53
	add.s32 	%r1188, %r4, %r1409;
	add.s32 	%r1189, %r1188, 64;
	add.s32 	%r1190, %r1188, 72;
	add.s32 	%r1191, %r1188, 80;
	.loc	1 97 72
	add.s32 	%r1192, %r1188, 88;
	setp.lt.s32 	%p35, %r1189, %r145;
	setp.lt.s32 	%p36, %r1190, %r145;
	setp.lt.s32 	%p37, %r1191, %r145;
	setp.lt.s32 	%p38, %r1192, %r145;
	.loc	1 97 20
	shl.b32 	%r1193, %r1445, 14;
	add.s32 	%r1195, %r268, %r1193;
	add.s32 	%r995, %r1195, %r267;
	add.s32 	%r997, %r1195, %r270;
	add.s32 	%r999, %r1195, %r272;
	add.s32 	%r1001, %r1195, %r274;
	selp.b32 	%r1200, 16, 0, %p35;
	selp.b32 	%r996, %r1200, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r995 + 0 ], [ %rd52 + 0 ], 0x10, %r996;
	// end inline asm
	selp.b32 	%r1201, 16, 0, %p36;
	selp.b32 	%r998, %r1201, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r997 + 0 ], [ %rd53 + 0 ], 0x10, %r998;
	// end inline asm
	selp.b32 	%r1202, 16, 0, %p37;
	selp.b32 	%r1000, %r1202, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r999 + 0 ], [ %rd54 + 0 ], 0x10, %r1000;
	// end inline asm
	selp.b32 	%r1203, 16, 0, %p38;
	selp.b32 	%r1002, %r1203, 0, %p32;
	// begin inline asm
	@%p1 cp.async.cg.shared.global [ %r1001 + 0 ], [ %rd55 + 0 ], 0x10, %r1002;
	// end inline asm
	// begin inline asm
	cp.async.commit_group ;
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1204, %r1444, 1;
	setp.lt.s32 	%p39, %r1204, 2;
	selp.b32 	%r1444, %r1204, 0, %p39;
	.loc	1 96 20
	shl.b32 	%r1205, %r1444, 13;
	add.s32 	%r1443, %r260, %r1205;
	// begin inline asm
	cp.async.wait_group 0x2;
	// end inline asm
	bar.sync 	0;
	.loc	1 97 20
	shl.b32 	%r1206, %r1444, 14;
	add.s32 	%r1442, %r268, %r1206;
	.loc	1 96 20
	add.s32 	%r1007, %r1443, %r285;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1438, %r1439, %r1440, %r1441 }, [ %r1007 + 0 ];
	// end inline asm
	add.s32 	%r1012, %r1007, 2048;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1434, %r1435, %r1436, %r1437 }, [ %r1012 + 0 ];
	// end inline asm
	add.s32 	%r1017, %r1007, 4096;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1430, %r1431, %r1432, %r1433 }, [ %r1017 + 0 ];
	// end inline asm
	add.s32 	%r1022, %r1007, 6144;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.shared.b16 { %r1426, %r1427, %r1428, %r1429 }, [ %r1022 + 0 ];
	// end inline asm
	.loc	1 97 20
	add.s32 	%r1027, %r1442, %r291;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1422, %r1423, %r1424, %r1425 }, [ %r1027 + 0 ];
	// end inline asm
	add.s32 	%r1032, %r1442, %r295;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1418, %r1419, %r1420, %r1421 }, [ %r1032 + 0 ];
	// end inline asm
	add.s32 	%r1037, %r1442, %r299;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1414, %r1415, %r1416, %r1417 }, [ %r1037 + 0 ];
	// end inline asm
	add.s32 	%r1042, %r1442, %r303;
	// begin inline asm
	ldmatrix.sync.aligned.m8n8.x4.trans.shared.b16 { %r1410, %r1411, %r1412, %r1413 }, [ %r1042 + 0 ];
	// end inline asm
	.loc	1 93 22
	add.s32 	%r1446, %r1446, 1;
	add.s64 	%rd109, %rd109, %rd10;
	add.s64 	%rd108, %rd108, 64;
	add.s64 	%rd107, %rd107, 64;
	add.s32 	%r1409, %r1409, 32;
	setp.lt.s32 	%p40, %r1446, %r11;
	@%p40 bra 	$L__BB0_2;
$L__BB0_3:
	.loc	1 74 51
	or.b32  	%r1272, %r1, %r4;
	.loc	1 74 38
	or.b32  	%r1273, %r1272, 120;
	.loc	1 83 33
	setp.lt.s32 	%p59, %r1273, %r143;
	.loc	1 83 58
	setp.lt.s32 	%p60, %r10, %r144;
	.loc	1 83 39
	and.pred  	%p58, %p59, %p60;
	.loc	1 74 38
	or.b32  	%r1274, %r1272, 112;
	.loc	1 83 33
	setp.lt.s32 	%p61, %r1274, %r143;
	.loc	1 83 39
	and.pred  	%p57, %p61, %p60;
	.loc	1 74 38
	or.b32  	%r1275, %r1272, 104;
	.loc	1 83 33
	setp.lt.s32 	%p62, %r1275, %r143;
	.loc	1 83 39
	and.pred  	%p56, %p62, %p60;
	.loc	1 74 38
	or.b32  	%r1276, %r1272, 96;
	.loc	1 83 33
	setp.lt.s32 	%p63, %r1276, %r143;
	.loc	1 83 39
	and.pred  	%p55, %p63, %p60;
	.loc	1 74 38
	or.b32  	%r1277, %r1272, 88;
	.loc	1 83 33
	setp.lt.s32 	%p64, %r1277, %r143;
	.loc	1 83 39
	and.pred  	%p54, %p64, %p60;
	.loc	1 74 38
	or.b32  	%r1278, %r1272, 80;
	.loc	1 83 33
	setp.lt.s32 	%p65, %r1278, %r143;
	.loc	1 83 39
	and.pred  	%p53, %p65, %p60;
	.loc	1 74 38
	or.b32  	%r1279, %r1272, 72;
	.loc	1 83 33
	setp.lt.s32 	%p66, %r1279, %r143;
	.loc	1 83 39
	and.pred  	%p52, %p66, %p60;
	.loc	1 74 38
	or.b32  	%r1280, %r1272, 64;
	.loc	1 83 33
	setp.lt.s32 	%p67, %r1280, %r143;
	.loc	1 83 39
	and.pred  	%p51, %p67, %p60;
	.loc	1 74 38
	or.b32  	%r1281, %r1, %r21;
	.loc	1 83 33
	setp.lt.s32 	%p68, %r1281, %r143;
	.loc	1 83 39
	and.pred  	%p50, %p68, %p60;
	.loc	1 74 38
	or.b32  	%r1282, %r1, %r20;
	.loc	1 83 33
	setp.lt.s32 	%p69, %r1282, %r143;
	.loc	1 83 39
	and.pred  	%p49, %p69, %p60;
	.loc	1 74 38
	or.b32  	%r1283, %r1, %r19;
	.loc	1 83 33
	setp.lt.s32 	%p70, %r1283, %r143;
	.loc	1 83 39
	and.pred  	%p48, %p70, %p60;
	.loc	1 74 38
	or.b32  	%r1284, %r1, %r18;
	.loc	1 83 33
	setp.lt.s32 	%p71, %r1284, %r143;
	.loc	1 83 39
	and.pred  	%p47, %p71, %p60;
	.loc	1 74 38
	or.b32  	%r1285, %r1, %r7;
	.loc	1 83 33
	setp.lt.s32 	%p72, %r1285, %r143;
	.loc	1 83 39
	and.pred  	%p46, %p72, %p60;
	.loc	1 74 38
	or.b32  	%r1286, %r1, %r6;
	.loc	1 83 33
	setp.lt.s32 	%p73, %r1286, %r143;
	.loc	1 83 39
	and.pred  	%p45, %p73, %p60;
	.loc	1 74 38
	or.b32  	%r1287, %r1, %r5;
	.loc	1 83 33
	setp.lt.s32 	%p74, %r1287, %r143;
	.loc	1 83 39
	and.pred  	%p44, %p74, %p60;
	.loc	1 83 33
	setp.lt.s32 	%p75, %r1272, %r143;
	.loc	1 83 39
	and.pred  	%p43, %p75, %p60;
	.loc	1 82 33
	mul.lo.s32 	%r1288, %r1273, %r146;
	.loc	1 82 21
	mul.wide.s32 	%rd73, %r1288, 2;
	add.s64 	%rd74, %rd24, %rd73;
	.loc	1 82 52
	mul.wide.s32 	%rd75, %r10, 2;
	add.s64 	%rd72, %rd74, %rd75;
	.loc	1 82 33
	shl.b32 	%r1289, %r146, 3;
	sub.s32 	%r1290, %r1288, %r1289;
	.loc	1 82 21
	mul.wide.s32 	%rd76, %r1290, 2;
	add.s64 	%rd77, %rd24, %rd76;
	.loc	1 82 52
	add.s64 	%rd71, %rd77, %rd75;
	.loc	1 82 33
	sub.s32 	%r1291, %r1290, %r1289;
	.loc	1 82 21
	mul.wide.s32 	%rd78, %r1291, 2;
	add.s64 	%rd79, %rd24, %rd78;
	.loc	1 82 52
	add.s64 	%rd70, %rd79, %rd75;
	.loc	1 82 33
	sub.s32 	%r1292, %r1291, %r1289;
	.loc	1 82 21
	mul.wide.s32 	%rd80, %r1292, 2;
	add.s64 	%rd81, %rd24, %rd80;
	.loc	1 82 52
	add.s64 	%rd69, %rd81, %rd75;
	.loc	1 82 33
	sub.s32 	%r1293, %r1292, %r1289;
	.loc	1 82 21
	mul.wide.s32 	%rd82, %r1293, 2;
	add.s64 	%rd83, %rd24, %rd82;
	.loc	1 82 52
	add.s64 	%rd68, %rd83, %rd75;
	.loc	1 82 33
	sub.s32 	%r1294, %r1293, %r1289;
	.loc	1 82 21
	mul.wide.s32 	%rd84, %r1294, 2;
	add.s64 	%rd85, %rd24, %rd84;
	.loc	1 82 52
	add.s64 	%rd67, %rd85, %rd75;
	.loc	1 82 33
	sub.s32 	%r1295, %r1294, %r1289;
	.loc	1 82 21
	mul.wide.s32 	%rd86, %r1295, 2;
	add.s64 	%rd87, %rd24, %rd86;
	.loc	1 82 52
	add.s64 	%rd66, %rd87, %rd75;
	.loc	1 82 33
	sub.s32 	%r1296, %r1295, %r1289;
	.loc	1 82 21
	mul.wide.s32 	%rd88, %r1296, 2;
	add.s64 	%rd89, %rd24, %rd88;
	.loc	1 82 52
	add.s64 	%rd65, %rd89, %rd75;
	.loc	1 82 33
	mul.lo.s32 	%r1297, %r1281, %r146;
	.loc	1 82 21
	mul.wide.s32 	%rd90, %r1297, 2;
	add.s64 	%rd91, %rd24, %rd90;
	.loc	1 82 52
	add.s64 	%rd64, %rd91, %rd75;
	.loc	1 82 33
	mul.lo.s32 	%r1298, %r1282, %r146;
	.loc	1 82 21
	mul.wide.s32 	%rd92, %r1298, 2;
	add.s64 	%rd93, %rd24, %rd92;
	.loc	1 82 52
	add.s64 	%rd63, %rd93, %rd75;
	.loc	1 82 33
	mul.lo.s32 	%r1299, %r1283, %r146;
	.loc	1 82 21
	mul.wide.s32 	%rd94, %r1299, 2;
	add.s64 	%rd95, %rd24, %rd94;
	.loc	1 82 52
	add.s64 	%rd62, %rd95, %rd75;
	.loc	1 82 33
	mul.lo.s32 	%r1300, %r1284, %r146;
	.loc	1 82 21
	mul.wide.s32 	%rd96, %r1300, 2;
	add.s64 	%rd97, %rd24, %rd96;
	.loc	1 82 52
	add.s64 	%rd61, %rd97, %rd75;
	.loc	1 82 33
	mul.lo.s32 	%r1301, %r1285, %r146;
	.loc	1 82 21
	mul.wide.s32 	%rd98, %r1301, 2;
	add.s64 	%rd99, %rd24, %rd98;
	.loc	1 82 52
	add.s64 	%rd60, %rd99, %rd75;
	.loc	1 82 33
	mul.lo.s32 	%r1302, %r1286, %r146;
	.loc	1 82 21
	mul.wide.s32 	%rd100, %r1302, 2;
	add.s64 	%rd101, %rd24, %rd100;
	.loc	1 82 52
	add.s64 	%rd59, %rd101, %rd75;
	.loc	1 82 33
	mul.lo.s32 	%r1303, %r1287, %r146;
	.loc	1 82 21
	mul.wide.s32 	%rd102, %r1303, 2;
	add.s64 	%rd103, %rd24, %rd102;
	.loc	1 82 52
	add.s64 	%rd58, %rd103, %rd75;
	.loc	1 82 33
	mul.lo.s32 	%r1304, %r1272, %r146;
	.loc	1 82 21
	mul.wide.s32 	%rd104, %r1304, 2;
	add.s64 	%rd105, %rd24, %rd104;
	.loc	1 82 52
	add.s64 	%rd57, %rd105, %rd75;
	.loc	1 75 51
	and.b32  	%r1305, %r2, 255;
	.loc	1 75 38
	or.b32  	%r1306, %r8, %r1305;
	.loc	1 93 22
	// begin inline asm
	cp.async.wait_group 0x0;
	// end inline asm
	bar.sync 	0;
	.loc	1 107 31
	mul.wide.s32 	%rd106, %r1306, 2;
	add.s64 	%rd56, %rd25, %rd106;
	.loc	1 108 32
	setp.lt.s32 	%p41, %r1306, %r144;
	mov.u16 	%rs388, 0;
	.loc	1 109 23
	// begin inline asm
	mov.u16 %rs387, 0x0;
	@%p41 ld.global.b16 { %rs387 }, [ %rd56 + 0 ];
	@!%p41 mov.u16 %rs387, %rs388;
	// end inline asm
	.loc	1 110 30
	shl.b32 	%r1307, %r1305, 1;
	add.s32 	%r1309, %r260, %r1307;
	st.shared.u16 	[%r1309], %rs387;
	bar.sync 	0;
	shl.b32 	%r1310, %r43, 4;
	shl.b32 	%r1311, %r2, 2;
	and.b32  	%r1312, %r1311, 12;
	or.b32  	%r1313, %r1310, %r1312;
	add.s32 	%r1314, %r260, %r1313;
	ld.shared.b32 	%r1315, [%r1314];
	mov.b32 	{%rs389, %rs390}, %r1315;
	add.s32 	%r1316, %r1314, 64;
	ld.shared.b32 	%r1317, [%r1314+64];
	mov.b32 	{%rs391, %rs392}, %r1317;
	add.s32 	%r1318, %r1314, 128;
	ld.shared.b32 	%r1319, [%r1314+128];
	mov.b32 	{%rs393, %rs394}, %r1319;
	add.s32 	%r1320, %r1314, 192;
	ld.shared.b32 	%r1321, [%r1314+192];
	mov.b32 	{%rs395, %rs396}, %r1321;
	add.s32 	%r1322, %r1314, 256;
	ld.shared.b32 	%r1323, [%r1314+256];
	mov.b32 	{%rs397, %rs398}, %r1323;
	add.s32 	%r1324, %r1314, 320;
	ld.shared.b32 	%r1325, [%r1314+320];
	mov.b32 	{%rs399, %rs400}, %r1325;
	add.s32 	%r1326, %r1314, 384;
	ld.shared.b32 	%r1327, [%r1314+384];
	mov.b32 	{%rs401, %rs402}, %r1327;
	add.s32 	%r1328, %r1314, 448;
	ld.shared.b32 	%r1329, [%r1314+448];
	mov.b32 	{%rs403, %rs404}, %r1329;
	.loc	1 111 23
	add.f16 	%rs405, %rs661, %rs389;
	add.f16 	%rs406, %rs662, %rs390;
	add.f16 	%rs407, %rs663, %rs389;
	add.f16 	%rs408, %rs664, %rs390;
	add.f16 	%rs409, %rs665, %rs391;
	add.f16 	%rs410, %rs666, %rs392;
	add.f16 	%rs411, %rs667, %rs391;
	add.f16 	%rs412, %rs668, %rs392;
	add.f16 	%rs413, %rs669, %rs393;
	add.f16 	%rs414, %rs670, %rs394;
	add.f16 	%rs415, %rs671, %rs393;
	add.f16 	%rs416, %rs672, %rs394;
	add.f16 	%rs417, %rs673, %rs395;
	add.f16 	%rs418, %rs674, %rs396;
	add.f16 	%rs419, %rs675, %rs395;
	add.f16 	%rs420, %rs676, %rs396;
	add.f16 	%rs421, %rs677, %rs397;
	add.f16 	%rs422, %rs678, %rs398;
	add.f16 	%rs423, %rs679, %rs397;
	add.f16 	%rs424, %rs680, %rs398;
	add.f16 	%rs425, %rs681, %rs399;
	add.f16 	%rs426, %rs682, %rs400;
	add.f16 	%rs427, %rs683, %rs399;
	add.f16 	%rs428, %rs684, %rs400;
	add.f16 	%rs429, %rs685, %rs401;
	add.f16 	%rs430, %rs686, %rs402;
	add.f16 	%rs431, %rs687, %rs401;
	add.f16 	%rs432, %rs688, %rs402;
	add.f16 	%rs433, %rs689, %rs403;
	add.f16 	%rs434, %rs690, %rs404;
	add.f16 	%rs435, %rs691, %rs403;
	add.f16 	%rs436, %rs692, %rs404;
	add.f16 	%rs437, %rs693, %rs389;
	add.f16 	%rs438, %rs694, %rs390;
	add.f16 	%rs439, %rs695, %rs389;
	add.f16 	%rs440, %rs696, %rs390;
	add.f16 	%rs441, %rs697, %rs391;
	add.f16 	%rs442, %rs698, %rs392;
	add.f16 	%rs443, %rs699, %rs391;
	add.f16 	%rs444, %rs700, %rs392;
	add.f16 	%rs445, %rs701, %rs393;
	add.f16 	%rs446, %rs702, %rs394;
	add.f16 	%rs447, %rs703, %rs393;
	add.f16 	%rs448, %rs704, %rs394;
	add.f16 	%rs449, %rs705, %rs395;
	add.f16 	%rs450, %rs706, %rs396;
	add.f16 	%rs451, %rs707, %rs395;
	add.f16 	%rs452, %rs708, %rs396;
	add.f16 	%rs453, %rs709, %rs397;
	add.f16 	%rs454, %rs710, %rs398;
	add.f16 	%rs455, %rs711, %rs397;
	add.f16 	%rs456, %rs712, %rs398;
	add.f16 	%rs457, %rs713, %rs399;
	add.f16 	%rs458, %rs714, %rs400;
	add.f16 	%rs459, %rs715, %rs399;
	add.f16 	%rs460, %rs716, %rs400;
	add.f16 	%rs461, %rs717, %rs401;
	add.f16 	%rs462, %rs718, %rs402;
	add.f16 	%rs463, %rs719, %rs401;
	add.f16 	%rs464, %rs720, %rs402;
	add.f16 	%rs465, %rs721, %rs403;
	add.f16 	%rs466, %rs722, %rs404;
	add.f16 	%rs467, %rs723, %rs403;
	add.f16 	%rs468, %rs724, %rs404;
	add.f16 	%rs469, %rs725, %rs389;
	add.f16 	%rs470, %rs726, %rs390;
	add.f16 	%rs471, %rs727, %rs389;
	add.f16 	%rs472, %rs728, %rs390;
	add.f16 	%rs473, %rs729, %rs391;
	add.f16 	%rs474, %rs730, %rs392;
	add.f16 	%rs475, %rs731, %rs391;
	add.f16 	%rs476, %rs732, %rs392;
	add.f16 	%rs477, %rs733, %rs393;
	add.f16 	%rs478, %rs734, %rs394;
	add.f16 	%rs479, %rs735, %rs393;
	add.f16 	%rs480, %rs736, %rs394;
	add.f16 	%rs481, %rs737, %rs395;
	add.f16 	%rs482, %rs738, %rs396;
	add.f16 	%rs483, %rs739, %rs395;
	add.f16 	%rs484, %rs740, %rs396;
	add.f16 	%rs485, %rs741, %rs397;
	add.f16 	%rs486, %rs742, %rs398;
	add.f16 	%rs487, %rs743, %rs397;
	add.f16 	%rs488, %rs744, %rs398;
	add.f16 	%rs489, %rs745, %rs399;
	add.f16 	%rs490, %rs746, %rs400;
	add.f16 	%rs491, %rs747, %rs399;
	add.f16 	%rs492, %rs748, %rs400;
	add.f16 	%rs493, %rs749, %rs401;
	add.f16 	%rs494, %rs750, %rs402;
	add.f16 	%rs495, %rs751, %rs401;
	add.f16 	%rs496, %rs752, %rs402;
	add.f16 	%rs497, %rs753, %rs403;
	add.f16 	%rs498, %rs754, %rs404;
	add.f16 	%rs499, %rs755, %rs403;
	add.f16 	%rs500, %rs756, %rs404;
	add.f16 	%rs501, %rs757, %rs389;
	add.f16 	%rs502, %rs758, %rs390;
	add.f16 	%rs503, %rs759, %rs389;
	add.f16 	%rs504, %rs760, %rs390;
	add.f16 	%rs505, %rs761, %rs391;
	add.f16 	%rs506, %rs762, %rs392;
	add.f16 	%rs507, %rs763, %rs391;
	add.f16 	%rs508, %rs764, %rs392;
	add.f16 	%rs509, %rs765, %rs393;
	add.f16 	%rs510, %rs766, %rs394;
	add.f16 	%rs511, %rs767, %rs393;
	add.f16 	%rs512, %rs768, %rs394;
	add.f16 	%rs513, %rs769, %rs395;
	add.f16 	%rs514, %rs770, %rs396;
	add.f16 	%rs515, %rs771, %rs395;
	add.f16 	%rs516, %rs772, %rs396;
	add.f16 	%rs517, %rs773, %rs397;
	add.f16 	%rs518, %rs774, %rs398;
	add.f16 	%rs519, %rs775, %rs397;
	add.f16 	%rs520, %rs776, %rs398;
	add.f16 	%rs521, %rs777, %rs399;
	add.f16 	%rs522, %rs778, %rs400;
	add.f16 	%rs523, %rs779, %rs399;
	add.f16 	%rs524, %rs780, %rs400;
	add.f16 	%rs525, %rs781, %rs401;
	add.f16 	%rs526, %rs782, %rs402;
	add.f16 	%rs527, %rs783, %rs401;
	add.f16 	%rs528, %rs784, %rs402;
	add.f16 	%rs529, %rs785, %rs403;
	add.f16 	%rs530, %rs786, %rs404;
	add.f16 	%rs531, %rs787, %rs403;
	add.f16 	%rs532, %rs788, %rs404;
	.loc	1 128 21
	bar.sync 	0;
	shr.u32 	%r1330, %r3, 2;
	or.b32  	%r1331, %r1330, %r24;
	mul.lo.s32 	%r1332, %r1331, 528;
	add.s32 	%r1333, %r1314, %r1332;
	mov.b32 	%r1334, {%rs405, %rs406};
	st.shared.b32 	[%r1333], %r1334;
	mov.b32 	%r1335, {%rs407, %rs408};
	st.shared.b32 	[%r1333+4224], %r1335;
	mov.b32 	%r1336, {%rs409, %rs410};
	st.shared.b32 	[%r1333+64], %r1336;
	add.s32 	%r1337, %r1316, %r1332;
	mov.b32 	%r1338, {%rs411, %rs412};
	st.shared.b32 	[%r1337+4224], %r1338;
	mov.b32 	%r1339, {%rs413, %rs414};
	st.shared.b32 	[%r1333+128], %r1339;
	add.s32 	%r1340, %r1318, %r1332;
	mov.b32 	%r1341, {%rs415, %rs416};
	st.shared.b32 	[%r1340+4224], %r1341;
	mov.b32 	%r1342, {%rs417, %rs418};
	st.shared.b32 	[%r1333+192], %r1342;
	add.s32 	%r1343, %r1320, %r1332;
	mov.b32 	%r1344, {%rs419, %rs420};
	st.shared.b32 	[%r1343+4224], %r1344;
	mov.b32 	%r1345, {%rs421, %rs422};
	st.shared.b32 	[%r1333+256], %r1345;
	add.s32 	%r1346, %r1322, %r1332;
	mov.b32 	%r1347, {%rs423, %rs424};
	st.shared.b32 	[%r1346+4224], %r1347;
	mov.b32 	%r1348, {%rs425, %rs426};
	st.shared.b32 	[%r1333+320], %r1348;
	add.s32 	%r1349, %r1324, %r1332;
	mov.b32 	%r1350, {%rs427, %rs428};
	st.shared.b32 	[%r1349+4224], %r1350;
	mov.b32 	%r1351, {%rs429, %rs430};
	st.shared.b32 	[%r1333+384], %r1351;
	add.s32 	%r1352, %r1326, %r1332;
	mov.b32 	%r1353, {%rs431, %rs432};
	st.shared.b32 	[%r1352+4224], %r1353;
	mov.b32 	%r1354, {%rs433, %rs434};
	st.shared.b32 	[%r1333+448], %r1354;
	add.s32 	%r1355, %r1328, %r1332;
	mov.b32 	%r1356, {%rs435, %rs436};
	st.shared.b32 	[%r1355+4224], %r1356;
	bar.sync 	0;
	shl.b32 	%r1357, %r3, 3;
	mad.lo.s32 	%r1358, %r4, 264, %r1357;
	shl.b32 	%r1359, %r1358, 1;
	add.s32 	%r1360, %r260, %r1359;
	ld.shared.v4.u32 	{%r1208, %r1209, %r1210, %r1211}, [%r1360];
	ld.shared.v4.u32 	{%r1212, %r1213, %r1214, %r1215}, [%r1360+4224];
	ld.shared.v4.u32 	{%r1216, %r1217, %r1218, %r1219}, [%r1360+8448];
	ld.shared.v4.u32 	{%r1220, %r1221, %r1222, %r1223}, [%r1360+12672];
	bar.sync 	0;
	mov.b32 	%r1361, {%rs437, %rs438};
	st.shared.b32 	[%r1333], %r1361;
	mov.b32 	%r1362, {%rs439, %rs440};
	st.shared.b32 	[%r1333+4224], %r1362;
	mov.b32 	%r1363, {%rs441, %rs442};
	st.shared.b32 	[%r1333+64], %r1363;
	mov.b32 	%r1364, {%rs443, %rs444};
	st.shared.b32 	[%r1337+4224], %r1364;
	mov.b32 	%r1365, {%rs445, %rs446};
	st.shared.b32 	[%r1333+128], %r1365;
	mov.b32 	%r1366, {%rs447, %rs448};
	st.shared.b32 	[%r1340+4224], %r1366;
	mov.b32 	%r1367, {%rs449, %rs450};
	st.shared.b32 	[%r1333+192], %r1367;
	mov.b32 	%r1368, {%rs451, %rs452};
	st.shared.b32 	[%r1343+4224], %r1368;
	mov.b32 	%r1369, {%rs453, %rs454};
	st.shared.b32 	[%r1333+256], %r1369;
	mov.b32 	%r1370, {%rs455, %rs456};
	st.shared.b32 	[%r1346+4224], %r1370;
	mov.b32 	%r1371, {%rs457, %rs458};
	st.shared.b32 	[%r1333+320], %r1371;
	mov.b32 	%r1372, {%rs459, %rs460};
	st.shared.b32 	[%r1349+4224], %r1372;
	mov.b32 	%r1373, {%rs461, %rs462};
	st.shared.b32 	[%r1333+384], %r1373;
	mov.b32 	%r1374, {%rs463, %rs464};
	st.shared.b32 	[%r1352+4224], %r1374;
	mov.b32 	%r1375, {%rs465, %rs466};
	st.shared.b32 	[%r1333+448], %r1375;
	mov.b32 	%r1376, {%rs467, %rs468};
	st.shared.b32 	[%r1355+4224], %r1376;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1224, %r1225, %r1226, %r1227}, [%r1360];
	ld.shared.v4.u32 	{%r1228, %r1229, %r1230, %r1231}, [%r1360+4224];
	ld.shared.v4.u32 	{%r1232, %r1233, %r1234, %r1235}, [%r1360+8448];
	ld.shared.v4.u32 	{%r1236, %r1237, %r1238, %r1239}, [%r1360+12672];
	bar.sync 	0;
	mov.b32 	%r1377, {%rs469, %rs470};
	st.shared.b32 	[%r1333], %r1377;
	mov.b32 	%r1378, {%rs471, %rs472};
	st.shared.b32 	[%r1333+4224], %r1378;
	mov.b32 	%r1379, {%rs473, %rs474};
	st.shared.b32 	[%r1333+64], %r1379;
	mov.b32 	%r1380, {%rs475, %rs476};
	st.shared.b32 	[%r1337+4224], %r1380;
	mov.b32 	%r1381, {%rs477, %rs478};
	st.shared.b32 	[%r1333+128], %r1381;
	mov.b32 	%r1382, {%rs479, %rs480};
	st.shared.b32 	[%r1340+4224], %r1382;
	mov.b32 	%r1383, {%rs481, %rs482};
	st.shared.b32 	[%r1333+192], %r1383;
	mov.b32 	%r1384, {%rs483, %rs484};
	st.shared.b32 	[%r1343+4224], %r1384;
	mov.b32 	%r1385, {%rs485, %rs486};
	st.shared.b32 	[%r1333+256], %r1385;
	mov.b32 	%r1386, {%rs487, %rs488};
	st.shared.b32 	[%r1346+4224], %r1386;
	mov.b32 	%r1387, {%rs489, %rs490};
	st.shared.b32 	[%r1333+320], %r1387;
	mov.b32 	%r1388, {%rs491, %rs492};
	st.shared.b32 	[%r1349+4224], %r1388;
	mov.b32 	%r1389, {%rs493, %rs494};
	st.shared.b32 	[%r1333+384], %r1389;
	mov.b32 	%r1390, {%rs495, %rs496};
	st.shared.b32 	[%r1352+4224], %r1390;
	mov.b32 	%r1391, {%rs497, %rs498};
	st.shared.b32 	[%r1333+448], %r1391;
	mov.b32 	%r1392, {%rs499, %rs500};
	st.shared.b32 	[%r1355+4224], %r1392;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1240, %r1241, %r1242, %r1243}, [%r1360];
	ld.shared.v4.u32 	{%r1244, %r1245, %r1246, %r1247}, [%r1360+4224];
	ld.shared.v4.u32 	{%r1248, %r1249, %r1250, %r1251}, [%r1360+8448];
	ld.shared.v4.u32 	{%r1252, %r1253, %r1254, %r1255}, [%r1360+12672];
	bar.sync 	0;
	mov.b32 	%r1393, {%rs501, %rs502};
	st.shared.b32 	[%r1333], %r1393;
	mov.b32 	%r1394, {%rs503, %rs504};
	st.shared.b32 	[%r1333+4224], %r1394;
	mov.b32 	%r1395, {%rs505, %rs506};
	st.shared.b32 	[%r1333+64], %r1395;
	mov.b32 	%r1396, {%rs507, %rs508};
	st.shared.b32 	[%r1337+4224], %r1396;
	mov.b32 	%r1397, {%rs509, %rs510};
	st.shared.b32 	[%r1333+128], %r1397;
	mov.b32 	%r1398, {%rs511, %rs512};
	st.shared.b32 	[%r1340+4224], %r1398;
	mov.b32 	%r1399, {%rs513, %rs514};
	st.shared.b32 	[%r1333+192], %r1399;
	mov.b32 	%r1400, {%rs515, %rs516};
	st.shared.b32 	[%r1343+4224], %r1400;
	mov.b32 	%r1401, {%rs517, %rs518};
	st.shared.b32 	[%r1333+256], %r1401;
	mov.b32 	%r1402, {%rs519, %rs520};
	st.shared.b32 	[%r1346+4224], %r1402;
	mov.b32 	%r1403, {%rs521, %rs522};
	st.shared.b32 	[%r1333+320], %r1403;
	mov.b32 	%r1404, {%rs523, %rs524};
	st.shared.b32 	[%r1349+4224], %r1404;
	mov.b32 	%r1405, {%rs525, %rs526};
	st.shared.b32 	[%r1333+384], %r1405;
	mov.b32 	%r1406, {%rs527, %rs528};
	st.shared.b32 	[%r1352+4224], %r1406;
	mov.b32 	%r1407, {%rs529, %rs530};
	st.shared.b32 	[%r1333+448], %r1407;
	mov.b32 	%r1408, {%rs531, %rs532};
	st.shared.b32 	[%r1355+4224], %r1408;
	bar.sync 	0;
	ld.shared.v4.u32 	{%r1256, %r1257, %r1258, %r1259}, [%r1360];
	ld.shared.v4.u32 	{%r1260, %r1261, %r1262, %r1263}, [%r1360+4224];
	ld.shared.v4.u32 	{%r1264, %r1265, %r1266, %r1267}, [%r1360+8448];
	ld.shared.v4.u32 	{%r1268, %r1269, %r1270, %r1271}, [%r1360+12672];
	// begin inline asm
	@%p43 st.global.v4.b32 [ %rd57 + 0 ], { %r1208, %r1209, %r1210, %r1211 };
	// end inline asm
	// begin inline asm
	@%p44 st.global.v4.b32 [ %rd58 + 0 ], { %r1212, %r1213, %r1214, %r1215 };
	// end inline asm
	// begin inline asm
	@%p45 st.global.v4.b32 [ %rd59 + 0 ], { %r1216, %r1217, %r1218, %r1219 };
	// end inline asm
	// begin inline asm
	@%p46 st.global.v4.b32 [ %rd60 + 0 ], { %r1220, %r1221, %r1222, %r1223 };
	// end inline asm
	// begin inline asm
	@%p47 st.global.v4.b32 [ %rd61 + 0 ], { %r1224, %r1225, %r1226, %r1227 };
	// end inline asm
	// begin inline asm
	@%p48 st.global.v4.b32 [ %rd62 + 0 ], { %r1228, %r1229, %r1230, %r1231 };
	// end inline asm
	// begin inline asm
	@%p49 st.global.v4.b32 [ %rd63 + 0 ], { %r1232, %r1233, %r1234, %r1235 };
	// end inline asm
	// begin inline asm
	@%p50 st.global.v4.b32 [ %rd64 + 0 ], { %r1236, %r1237, %r1238, %r1239 };
	// end inline asm
	// begin inline asm
	@%p51 st.global.v4.b32 [ %rd65 + 0 ], { %r1240, %r1241, %r1242, %r1243 };
	// end inline asm
	// begin inline asm
	@%p52 st.global.v4.b32 [ %rd66 + 0 ], { %r1244, %r1245, %r1246, %r1247 };
	// end inline asm
	// begin inline asm
	@%p53 st.global.v4.b32 [ %rd67 + 0 ], { %r1248, %r1249, %r1250, %r1251 };
	// end inline asm
	// begin inline asm
	@%p54 st.global.v4.b32 [ %rd68 + 0 ], { %r1252, %r1253, %r1254, %r1255 };
	// end inline asm
	// begin inline asm
	@%p55 st.global.v4.b32 [ %rd69 + 0 ], { %r1256, %r1257, %r1258, %r1259 };
	// end inline asm
	// begin inline asm
	@%p56 st.global.v4.b32 [ %rd70 + 0 ], { %r1260, %r1261, %r1262, %r1263 };
	// end inline asm
	// begin inline asm
	@%p57 st.global.v4.b32 [ %rd71 + 0 ], { %r1264, %r1265, %r1266, %r1267 };
	// end inline asm
	// begin inline asm
	@%p58 st.global.v4.b32 [ %rd72 + 0 ], { %r1268, %r1269, %r1270, %r1271 };
	// end inline asm
	.loc	1 128 4
	ret;
$L__tmp6:
$L__func_end0:

}
	.file	1 "/home/mike/Desktop/Descite/llm.c/dev/triton/compile_matmul_kernel_bias.py"
	.file	2 "/home/mike/Desktop/Descite/llm.c/venv/lib/python3.12/site-packages/triton/language/standard.py"
	.section	.debug_abbrev
	{
.b8 1
.b8 17
.b8 1
.b8 37
.b8 8
.b8 19
.b8 5
.b8 3
.b8 8
.b8 16
.b8 6
.b8 27
.b8 8
.b8 17
.b8 1
.b8 18
.b8 1
.b8 0
.b8 0
.b8 2
.b8 46
.b8 0
.b8 3
.b8 8
.b8 32
.b8 11
.b8 0
.b8 0
.b8 3
.b8 46
.b8 1
.b8 17
.b8 1
.b8 18
.b8 1
.b8 49
.b8 19
.b8 0
.b8 0
.b8 4
.b8 29
.b8 0
.b8 49
.b8 19
.b8 17
.b8 1
.b8 18
.b8 1
.b8 88
.b8 11
.b8 89
.b8 11
.b8 87
.b8 11
.b8 0
.b8 0
.b8 0
	}
	.section	.debug_info
	{
.b32 217
.b8 2
.b8 0
.b32 .debug_abbrev
.b8 8
.b8 1
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b8 2
.b8 0
.b8 99
.b8 111
.b8 109
.b8 112
.b8 105
.b8 108
.b8 101
.b8 95
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 46
.b8 112
.b8 121
.b8 0
.b32 .debug_line
.b8 47
.b8 104
.b8 111
.b8 109
.b8 101
.b8 47
.b8 109
.b8 105
.b8 107
.b8 101
.b8 47
.b8 68
.b8 101
.b8 115
.b8 107
.b8 116
.b8 111
.b8 112
.b8 47
.b8 68
.b8 101
.b8 115
.b8 99
.b8 105
.b8 116
.b8 101
.b8 47
.b8 108
.b8 108
.b8 109
.b8 46
.b8 99
.b8 47
.b8 100
.b8 101
.b8 118
.b8 47
.b8 116
.b8 114
.b8 105
.b8 116
.b8 111
.b8 110
.b8 0
.b64 $L__func_begin0
.b64 $L__func_end0
.b8 2
.b8 109
.b8 97
.b8 116
.b8 109
.b8 117
.b8 108
.b8 95
.b8 107
.b8 101
.b8 114
.b8 110
.b8 101
.b8 108
.b8 0
.b8 1
.b8 3
.b64 $L__func_begin0
.b64 $L__func_end0
.b32 110
.b8 4
.b32 110
.b64 $L__tmp1
.b64 $L__tmp2
.b8 1
.b8 58
.b8 27
.b8 4
.b32 110
.b64 $L__tmp2
.b64 $L__tmp3
.b8 1
.b8 59
.b8 27
.b8 4
.b32 110
.b64 $L__tmp4
.b64 $L__tmp5
.b8 1
.b8 93
.b8 33
.b8 0
.b8 0
	}
	.section	.debug_loc	{	}
)";

#define TRITON_MATMUL_KERNEL_8_SHARED_MEMORY_SIZE 49152
#define TRITON_MATMUL_KERNEL_8_BLOCK_SIZE_M 128
#define TRITON_MATMUL_KERNEL_8_BLOCK_SIZE_N 256
#define TRITON_MATMUL_KERNEL_8_NUM_WARPS 8
#define TRITON_MATMUL_KERNEL_8_FUNCTION_NAME "matmul_kernel_bias"
